(self.AMP=self.AMP||[]).push({n:"amp-bind",v:"1518203063064",f:(function(AMP){var v;function ba(a,c){function b(){}b.prototype=c.prototype;a.prototype=new b;a.prototype.constructor=a;for(var d in c)if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(c,d);e&&Object.defineProperty(a,d,e)}else a[d]=c[d]}var ca=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a}(this);function da(a,c){c=void 0===c?"":c;try{return decodeURIComponent(a)}catch(b){return c}};var ea=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;function fa(a){var c=Object.create(null);if(!a)return c;for(var b;b=ea.exec(a);){var d=da(b[1],b[1]),e=b[2]?da(b[2],b[2]):"";c[d]=e}return c};var ha="";function B(){var a,c=a||self,b;if(c.AMP_MODE)b=c.AMP_MODE;else{b=c;var d=fa(b.location.originalHash||b.location.hash),e=fa(b.location.search);ha||(ha=b.AMP_CONFIG&&b.AMP_CONFIG.v?b.AMP_CONFIG.v:"011518203063064");b=c.AMP_MODE={localDev:!1,development:!("1"!=d.development&&!b.AMP_DEV_MODE),examiner:"2"==d.development,filter:d.filter,minified:!0,lite:void 0!=e.amp_lite,test:!1,log:d.log,version:"1518203063064",rtvVersion:ha}}return b};var ia=Object.prototype.toString;function oa(a){if(!a)return[];for(var c=Array(a.length),b=0;b<a.length;b++)c[b]=a[b];return c}function pa(a){return"[object Object]"===ia.call(a)};function qa(a){var c=a.message,b=String(Math.random());a.message=b;if(a.message===b)return a.message=c,a;var c=Error(a.message),d;for(d in a)c[d]=a[d];c.stack=a.stack;return c}function ra(a){for(var c=null,b="",d=0;d<arguments.length;d++){var e=arguments[d];e instanceof Error&&!c?c=qa(e):(b&&(b+=" "),b+=e)}c?b&&(c.message=b+": "+c.message):c=Error(b);return c}function sa(a){var c=ra.apply(null,arguments);setTimeout(function(){self.reportError(c);throw c;})}self.log=self.log||{user:null,dev:null,userForEmbed:null};
var ta=self.log;function F(){if(!ta.user)throw Error("failed to call initLogConstructor");return ta.user}function ua(){if(ta.dev)return ta.dev;throw Error("failed to call initLogConstructor");};var va=Object.prototype.hasOwnProperty;function H(a){var c=Object.create(null);a&&Object.assign(c,a);return c}function wa(a,c){if(va.call(a,c))return a[c]}
function xa(a,c){var b=10,b=void 0===b?10:b,d=[],e=[];e.push({t:a,s:c,d:0});for(a={};0<e.length;){c=e.shift();a.t=c.t;a.s=c.s;a.d=c.d;if(d.includes(a.s))throw Error("Source object has a circular reference.");d.push(a.s);a.t!==a.s&&(a.d>b?Object.assign(a.t,a.s):(Object.keys(a.s).forEach(function(a){return function(b){var c=a.s[b];if(va.call(a.t,b)){var d=a.t[b];if(pa(c)&&pa(d)){e.push({t:d,s:c,d:a.d+1});return}}a.t[b]=c}}(a)),a={s:a.s,t:a.t,d:a.d}))}};function R(a,c){return c.length>a.length?!1:0==a.lastIndexOf(c,0)};var ya=self.AMP_CONFIG||{},za=ya.cdnUrl||"https://cdn.ampproject.org",Aa=("string"==typeof ya.cdnProxyRegex?new RegExp(ya.cdnProxyRegex):ya.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org$/,Ha=ya.errorReportingUrl||"https://amp-error-reporting.appspot.com/r";var Ia,Ja,Ka=/[?&]amp_js[^&]*/,La=/[?&]usqp[^&]*/;
function S(a){var c;Ia||(Ia=self.document.createElement("a"),Ja=self.UrlCache||(self.UrlCache=Object.create(null)));var b=Ja[a];if(b)return b;var d=Ia;d.href=a;d.protocol||(d.href=d.href);var e={href:d.href,protocol:d.protocol,host:d.host,hostname:d.hostname,port:"0"==d.port?"":d.port,pathname:d.pathname,search:d.search,hash:d.hash,origin:null};"/"!==e.pathname[0]&&(e.pathname="/"+e.pathname);if("http:"==e.protocol&&80==e.port||"https:"==e.protocol&&443==e.port)e.port="",e.host=e.hostname;e.origin=
d.origin&&"null"!=d.origin?d.origin:"data:"!=e.protocol&&e.host?e.protocol+"//"+e.host:e.href;var f=e,k=f;return c?k:Ja[a]=k}function Ma(a){"string"==typeof a&&(a=S(a));var c;(c="https:"==a.protocol||"localhost"==a.hostname)||(a=a.hostname,c=a.length-10,c=0<=c&&a.indexOf(".localhost",c)==c);return c}
function Na(a,c){var b;b=void 0===b?"source":b;F().assert(null!=a,"%s %s must be available",c,b);var d=a;F().assert(Ma(d)||/^(\/\/)/.test(d),'%s %s must start with "https://" or "//" or be relative and served from either https or from localhost. Invalid value: %s',c,b,d);return d}function Oa(a){"string"==typeof a&&(a=S(a));return Aa.test(a.origin)}
function Pa(a){"string"==typeof a&&(a=S(a));if(!Oa(a))return a.href;var c=a.pathname.split("/"),b=c[1];F().assert("a"==b||"c"==b||"v"==b,"Unknown path prefix in url %s",a.href);var d=c[2],e="s"==d?"https://"+decodeURIComponent(c[3]):"http://"+decodeURIComponent(d);F().assert(0<e.indexOf("."),"Expected a . in origin %s",e);c.splice(1,"s"==d?3:2);c=e+c.join("/");b=(b=a.search)&&"?"!=b?(b=b.replace(Ka,"").replace(La,"").replace(/^[?&]/,""))?"?"+b:"":"";return c+b+(a.hash||"")}
function Qa(a,c){"string"==typeof c&&(c=S(c));var b;if("function"==typeof URL)b=(new URL(a,c.href)).toString();else{b=a;var d=c;"string"==typeof d&&(d=S(d));b=b.replace(/\\/g,"/");var e=S(b);b=R(b.toLowerCase(),e.protocol)?e.href:R(b,"//")?d.protocol+b:R(b,"/")?d.origin+b:d.origin+d.pathname.replace(/\/[^/]*$/,"/")+b}return b};function Ra(a,c){try{return JSON.parse(a)}catch(b){c&&c(b)}}
function Sa(a,c,b){b=void 0===b?3:b;if(!isFinite(b))throw Error("depth arg must be finite: "+b);if(a===c)return!0;if(1>b||typeof a!==typeof c)return!1;if(Array.isArray(a)&&Array.isArray(c)){if(a.length!==c.length)return!1;for(var d=0;d<a.length;d++)if(!Sa(a[d],c[d],b-1))return!1;return!0}if(a&&c&&"object"===typeof a&&"object"===typeof c){var e=Object.keys(a),f=Object.keys(c);if(e.length!==f.length)return!1;for(d=0;d<e.length;d++){var k=e[d],l=a[k],h=c[k];if(!Sa(l,h,b-1))return!1}return!0}return!1}
;function Ta(a,c,b){if(a.nodeType){var d=Ua((a.ownerDocument||a).defaultView,c);if(d)return d}return!a.nodeType||b?T(a,c):null}function Va(a,c){var b=Wa(a);Ua(a,"bind");Xa(a,a,"bind",function(){return c});ab(a,"bind")}function Ua(a,c){var b=Wa(a);return a!=b&&bb(a,c)?ab(a,c):null}function U(a,c){a=Wa(a);return ab(a,c)}function T(a,c){a=cb(a);a=db(a);return ab(a,c)}function Wa(a){return a.__AMP_TOP||a}function cb(a){return a.nodeType?U((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}
function db(a){a=cb(a);return a.isSingleDoc()?a.win:a}function ab(a,c){bb(a,c);var b=eb(a);a=b[c];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}function Xa(a,c,b,d){var e=eb(a),f=e[b];f||(f=e[b]={obj:null,promise:null,resolve:null,context:null,ctor:null});f.ctor||f.obj||(f.ctor=d,f.context=c,f.resolve&&ab(a,b))}
function fb(a,c){var b=gb(a,c);if(b)return b;var d,e=new Promise(function(a){d=a});eb(a)[c]={obj:null,promise:e,resolve:d,context:null,ctor:null};return e}function gb(a,c){var b=eb(a)[c];if(b){if(b.promise)return b.promise;ab(a,c);return b.promise=Promise.resolve(b.obj)}return null}function eb(a){var c=a.services;c||(c=a.services={});return c}function bb(a,c){a=a.services&&a.services[c];return!(!a||!a.ctor&&!a.obj)};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
function hb(a,c,b){if(c(a))b();else{var d=a.ownerDocument.defaultView;if(d.MutationObserver){var e=new d.MutationObserver(function(){c(a)&&(e.disconnect(),b())});e.observe(a,{childList:!0})}else var f=d.setInterval(function(){c(a)&&(d.clearInterval(f),b())},5)}}function ib(a,c){hb(a.documentElement,function(){return!!a.body},c)}function jb(a){return new Promise(function(c){ib(a,c)})}var kb;
function lb(a){if(null==kb){var c=a.ownerDocument;try{var b=c.createElement("div"),d=c.createElement("div");b.appendChild(d);kb=b.querySelector(":scope div")===d}catch(e){kb=!1}}if(kb)return a.querySelectorAll(":scope AMP-BIND-MACRO");a.classList.add("i-amphtml-scoped");c=a.querySelectorAll(".i-amphtml-scoped AMP-BIND-MACRO");a.classList.remove("i-amphtml-scoped");return c}function mb(a,c){for(var b=0,d;void 0!==(d=a[b]);b++)c(d,b)}
function nb(a){return"SCRIPT"==a.tagName&&"APPLICATION/JSON"==a.getAttribute("type").toUpperCase()};function ob(a){return a.ampExtendedElements?!!a.ampExtendedElements["amp-bind"]:!1}function pb(a){var c=cb(a),b=gb(db(a),"bind");return b?b:Promise.resolve().then(function(){return ob(c.win)?fb(db(a),"bind"):c.whenBodyAvailable().then(function(){return ob(c.win)?fb(db(a),"bind"):null})})}function qb(a){var c=Ta(a,"bind");if(c)return Promise.resolve(c);if(a.nodeType){var c=(a.ownerDocument||a).defaultView,b=Wa(c);return c!==b?rb(c):pb(a)}return Promise.resolve(null)}
function rb(a){return Promise.resolve().then(function(){return ob(a)?fb(a,"bind"):jb(a.document).then(function(){return ob(a)?fb(a,"bind"):null})})};function sb(){var a=tb();return function(c){return setTimeout(c,a())}}function tb(){var a=0;return function(){var c=Math.pow(1.5,a++),b;b=c*(b||.3)*Math.random();.5<Math.random()&&(b*=-1);c+=b;return 1E3*c}};var ub,vb="Webkit webkit Moz moz ms O o".split(" ");function wb(a,c){var b=void 0;if(R(c,"--"))return c;ub||(ub=H());var d=ub[c];if(!d||b){d=c;if(void 0===a[c]){var e=c.charAt(0).toUpperCase()+c.slice(1);a:{for(var f=0;f<vb.length;f++){var k=vb[f]+e;if(void 0!==a[k]){e=k;break a}}e=""}var l=e;void 0!==a[l]&&(d=l)}b||(ub[c]=d)}return d}function xb(a,c,b){var d;(c=wb(a.style,c))&&(a.style[c]=d?b+d:b)}
function yb(a){var c=!1;if(void 0===c){var b;b=(b=wb(a.style,"display"))?a.style[b]:void 0;c="none"==b}xb(a,"display",c?"":"none")};var zb={"amp-dynamic-css-classes":"[custom-element=amp-dynamic-css-classes]",variant:"amp-experiment","amp-story":"amp-story[standalone]"};function Ab(a){var c=Eb(a).map(function(b){return U(a,"timer").timeoutPromise(3E3,fb(a,b),"Render timeout waiting for service "+b+" to be ready.")});return Promise.all(c)}function Eb(a){var c=a.document;return Object.keys(zb).filter(function(a){return c.querySelector(zb[a])})};function Fb(a){var c,b=a.defaultView;if(!b.__AMP_BODY_VISIBLE){var d=function(){b.__AMP_BODY_VISIBLE=!0;var c=a.body,d={opacity:1,visibility:"visible",animation:"none"},k;for(k in d)xb(c,k,d[k]);try{T(a,"resources").renderStarted()}catch(l){}};try{ib(a,function(){b.__AMP_BODY_VISIBLE||(b.__AMP_BODY_VISIBLE=!0,c?Ab(b).catch(function(a){sa(a);return[]}).then(function(c){d();0<c.length&&T(a,"resources").schedulePass(1,!0);try{var e=U(b,"performance");e.tick("mbv");e.flush()}catch(k){}}):d())})}catch(e){d(),
sa(e)}}};var Gb=self.AMPErrors||[];self.AMPErrors=Gb;function Hb(a){Hb=sb();return Hb(a)}function Ib(a){try{return JSON.stringify(a)}catch(c){return String(a)}}var Jb;
function V(a,c){try{var b;if(a)if(void 0!==a.message)a=qa(a),b=!0;else{var d=a;a=Error(Ib(d));a.origError=d}else a=Error("Unknown error");if(!a.reported){a.reported=!0;var e=c||a.associatedElement;e&&e.classList&&(e.classList.add("i-amphtml-error"),B().development&&(e.classList.add("i-amphtml-element-error"),e.setAttribute("error-message",a.message)));if(self.console){var f=console.error||console.log;a.messageArray?f.apply(console,a.messageArray):e?f.call(console,a.message,e):f.call(console,a.message)}e&&
e.oa&&e.oa("amp:error",a.message);Kb.call(void 0,void 0,void 0,void 0,void 0,a)}}catch(k){setTimeout(function(){throw k;})}}function Kb(a,c,b,d,e){this&&this.document&&Fb(this.document);if(!B().development){var f=!1;try{f=Lb()}catch(l){}if(!(f&&.01<Math.random())){var k=Mb(a,c,b,d,e,f);k&&(Nb(this,k),Hb(function(){var a=new XMLHttpRequest;a.open("POST",Ha,!0);a.send(JSON.stringify(k))}))}}}
function Nb(a,c){var b=U(a,"ampdoc");if(b.isSingleDoc()){var d=b.getAmpDoc(),e=d.getRootNode().documentElement,f=e.hasAttribute("report-errors-to-viewer");if(f){var k=T(d,"viewer");k.hasCapability("errorReporter")?k.isTrustedViewer().then(function(a){if(!a)return!1;k.sendMessage("error",c);return!0}):Promise.resolve(!1)}else Promise.resolve(!1)}else Promise.resolve(!1)}
function Mb(a,c,b,d,e,f){var k=!1;e&&(a=e.message?e.message:String(e),e.expected&&(k=!0));a||(a="Unknown error");if(!/_reported_/.test(a)&&"CANCELLED"!=a){var l=Math.random();if(-1!=a.indexOf("Failed to load:")||"Script error."==a)if(k=!0,.001<l)return;var h=0<=a.indexOf("\u200b\u200b\u200b");if(!(h&&.1<l)){var g=Object.create(null);g.v=B().rtvVersion;g.noAmp=f?"1":"0";g.m=a.replace("\u200b\u200b\u200b","");g.a=h?"1":"0";g.ex=k?"1":"0";var n="1p";self.context&&self.context.location?(g["3p"]="1",n=
"3p"):B().runtime&&(n=B().runtime);g.rt=n;f=self;g.ca=f.AMP_CONFIG&&f.AMP_CONFIG.canary?"1":"0";f=self;g.bt=f.AMP_CONFIG&&f.AMP_CONFIG.type?f.AMP_CONFIG.type:"unknown";self.location.ancestorOrigins&&self.location.ancestorOrigins[0]&&(g.or=self.location.ancestorOrigins[0]);self.viewerState&&(g.vs=self.viewerState);self.parent&&self.parent!=self&&(g.iem="1");if(self.AMP&&self.AMP.viewer){var r=self.AMP.viewer.getResolvedViewerUrl(),q=self.AMP.viewer.maybeGetMessagingOrigin();r&&(g.rvu=r);q&&(g.mso=
q)}Jb||(Jb=Ob());g.jse=Jb;var u=[];f=self.__AMP__EXPERIMENT_TOGGLES||null;for(var C in f)u.push(C+"="+(f[C]?"1":"0"));g.exps=u.join(",");e?(g.el=e.associatedElement?e.associatedElement.tagName:"u",e.args&&(g.args=JSON.stringify(e.args)),h||e.ignoreStack||!e.stack||(g.s=e.stack),e.message+=" _reported_"):(g.f=c||"",g.l=b||"",g.c=d||"");g.r=self.document.referrer;g.ae=Gb.join(",");g.fr=self.location.originalHash||self.location.hash;25<=Gb.length&&Gb.splice(0,Gb.length-25+1);Gb.push(a);return g}}}
function Lb(){for(var a=self.document.querySelectorAll("script[src]"),c=0;c<a.length;c++)if(!Oa(a[c].src.toLowerCase()))return!0;return!1}function Ob(){function a(){}a.prototype.t=function(){throw Error("message");};var c=new a;try{c.t()}catch(e){var b=e.stack;if(R(b,"t@"))return"Safari";if(-1<b.indexOf(".prototype.t@"))return"Firefox";var d=b.split("\n").pop();if(/\bat .* \(/i.test(d))return"IE";if(R(b,"Error: message"))return"Chrome"}return"unknown"};function Pb(a,c){for(var b=[],d=0,e=0;e<a.length;e++){var f=a[e];c(f,e,a)?(d<e&&(a[d]=f),d++):b.push(f)}d<a.length&&(a.length=d)};function Qb(a){return AMP.BaseElement.apply(this,arguments)||this}ba(Qb,AMP.BaseElement);v=Qb.prototype;v.getPriority=function(){return 1};v.isAlwaysFixed=function(){return!0};v.isLayoutSupported=function(){return!0};v.renderOutsideViewport=function(){return!0};v.O=function(){return"<amp-bind-macro> "+(this.element.getAttribute("id")||"<unknown id>")};function Rb(a,c,b){var d=void 0,d=void 0===d?".":d;b=void 0===b?0:b;var e=Na(c.getAttribute("src"),c),f=Ta(a,"url-replace",!0),k=1<=b?f.expandUrlAsync(e):Promise.resolve(e);return k.then(function(d){1==b&&f.collectUnwhitelistedVars(c).then(function(a){if(0<a.length){var b=c.tagName;F().error(b,"URL variable substitutions in CORS fetches triggered by amp-bind will soon require opt-in. Please add "+('data-amp-replace="'+a.join(" ")+'" to the ')+("<"+b+'> element. See "bit.ly/amp-var-subs" for details.'))}});
var e={};c.hasAttribute("credentials")?e.credentials=c.getAttribute("credentials"):e.requireAmpResponseSourceOrigin=!1;return U(a.win,"batched-xhr").fetchJson(d,e)}).then(function(a){return a.json()}).then(function(a){if(null==a)throw Error("Response is undefined.");var b;b=d||".";if("."!=b){b=b.split(".");for(var c=0;c<b.length;c++){var e=b[c];if(e&&a&&void 0!==a[e]&&(null==a||"object"!=typeof a?0:Object.prototype.hasOwnProperty.call(a,e)))a=a[e];else{a=void 0;break}}}b=a;return b})};function Sb(a){return AMP.BaseElement.apply(this,arguments)||this}ba(Sb,AMP.BaseElement);v=Sb.prototype;v.getPriority=function(){return 1};v.isAlwaysFixed=function(){return!0};v.isLayoutSupported=function(){return!0};v.activate=function(){var a=this.O();this.user().error(a,'Please use AMP.setState() action explicitly, e.g. on="submit-success:AMP.setState({myAmpState: event.response})"')};
v.buildCallback=function(){var a=this;yb(this.element);this.element.setAttribute("aria-hidden","true");T(this.getAmpDoc(),"viewer").whenFirstVisible().then(function(){return a.X()})};v.mutatedAttributesCallback=function(a){if(T(this.getAmpDoc(),"viewer").isVisible())void 0!==a.src&&Tb(this,!1);else{var c=this.O();ua().error(c,"Viewer must be visible before mutation.")}};v.renderOutsideViewport=function(){return!0};
v.X=function(){var a=this;this.element.hasAttribute("overridable")&&qb(this.element).then(function(c){c.makeStateKeyOverridable(a.element.getAttribute("id"))});0<this.element.children.length&&Ub(this);this.element.hasAttribute("src")&&Tb(this,!0)};
function Ub(a){var c=a.O(),b=a.element.children;if(1!=b.length)a.user().error(c,"Should contain exactly one <script> child.");else{var d=b[0];nb(d)?(b=Ra(d.textContent,function(b){a.user().error(c,"Failed to parse state. Is it valid JSON?",b)}),Vb(a,b,!0)):a.user().error(c,'State should be in a <script> tag with type="application/json".')}}function Wb(a,c,b){var d=c.getAttribute("src"),e=1;if(b||S(Pa(d)).origin==S(Pa(a.win.location)).origin)e=2;return Rb(a,c,e)}
function Tb(a,c){var b=a.getAmpDoc();Wb(b,a.element,c).then(function(b){Vb(a,b,c)})}function Vb(a,c,b){if(void 0!==c&&null!==c){var d=F().assert(a.element.id,"<amp-state> must have an id."),e=H();e[d]=c;qb(a.element).then(function(a){a.setState(e,b,!b)})}}v.O=function(){return"<amp-state> "+(this.element.getAttribute("id")||"<unknown id>")};function W(a,c,b){this.type=a;this.args=c;this.value=b};(function(){function a(a,b,c){var d;c=c||{};for(d=a.length;d--;c[a[d]]=b);return c}function c(){this.yy={}}var b=[1,7],d=[1,10],e=[1,11],f=[1,12],k=[1,13],l=[1,23],h=[1,17],g=[1,18],n=[1,19],r=[1,20],q=[1,21],u=[1,22],C=[1,26],A=[1,25],t=[1,27],E=[1,28],z=[1,29],I=[1,30],D=[1,31],K=[1,32],G=[1,33],L=[1,34],J=[1,35],M=[1,36],P=[1,37],Q=[1,38],w=[1,39],x=[1,41],y=[5,10,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,31,35,38,39,49],ja=[2,39],ka=[1,47],Ca=[1,52],ga=[1,54],X=[5,10,14,15,16,17,18,19,20,21,
22,23,24,25,26,27,28,35,39,49],Da=[1,75],la=[35,49],Ea=[10,35,39],Fa=[5,10,14,15,19,20,21,22,23,24,25,26,27,28,35,39,49],aa=[5,10,19,20,21,22,23,24,25,26,27,28,35,39,49],ma=[5,10,19,20,25,26,27,28,35,39,49],Ga=[10,35],na={trace:function O(){},yy:{},va:{error:2,result:3,expr:4,EOF:5,operation:6,invocation:7,member_access:8,"(":9,")":10,variable:11,literal:12,"!":13,"-":14,"+":15,"*":16,"/":17,"%":18,"&&":19,"||":20,"<=":21,"<":22,">=":23,">":24,"!=":25,"==":26,"?":27,":":28,NAME:29,args:30,".":31,
arrow_function:32,"=>":33,params:34,",":35,array:36,member:37,"[":38,"]":39,primitive:40,object_literal:41,array_literal:42,STRING:43,NUMBER:44,TRUE:45,FALSE:46,NULL:47,"{":48,"}":49,object:50,key_value:51,key:52,$accept:0,$end:1},S:{2:"error",5:"EOF",9:"(",10:")",13:"!",14:"-",15:"+",16:"*",17:"/",18:"%",19:"&&",20:"||",21:"<=",22:"<",23:">=",24:">",25:"!=",26:"==",27:"?",28:":",29:"NAME",31:".",33:"=>",35:",",38:"[",39:"]",43:"STRING",44:"NUMBER",45:"TRUE",46:"FALSE",47:"NULL",48:"{",49:"}"},ia:[0,
[3,2],[3,1],[4,1],[4,1],[4,1],[4,3],[4,1],[4,1],[6,2],[6,2],[6,2],[6,3],[6,3],[6,3],[6,3],[6,3],[6,3],[6,3],[6,3],[6,3],[6,3],[6,3],[6,3],[6,3],[6,5],[7,2],[7,4],[7,6],[32,4],[32,3],[32,5],[34,3],[34,3],[30,2],[30,3],[8,2],[37,2],[37,3],[11,1],[12,1],[12,1],[12,1],[40,1],[40,1],[40,1],[40,1],[40,1],[42,2],[42,3],[42,4],[36,1],[36,3],[41,2],[41,3],[41,4],[50,1],[50,3],[51,3],[52,1],[52,1],[52,3]],performAction:function Ba(a,b,c,d,e,p){var m=p.length-1;switch(e){case 1:return p[m-1];case 2:return"";
case 3:case 4:case 5:case 7:case 8:this.h=p[m];break;case 6:this.h=p[m-1];break;case 9:this.h=new W(12,[p[m]]);break;case 10:this.h=new W(13,[p[m]]);break;case 11:this.h=new W(14,[p[m]]);break;case 12:this.h=new W(15,[p[m-2],p[m]]);break;case 13:this.h=new W(16,[p[m-2],p[m]]);break;case 14:this.h=new W(17,[p[m-2],p[m]]);break;case 15:this.h=new W(18,[p[m-2],p[m]]);break;case 16:this.h=new W(19,[p[m-2],p[m]]);break;case 17:this.h=new W(20,[p[m-2],p[m]]);break;case 18:this.h=new W(21,[p[m-2],p[m]]);
break;case 19:this.h=new W(22,[p[m-2],p[m]]);break;case 20:this.h=new W(23,[p[m-2],p[m]]);break;case 21:this.h=new W(24,[p[m-2],p[m]]);break;case 22:this.h=new W(25,[p[m-2],p[m]]);break;case 23:this.h=new W(26,[p[m-2],p[m]]);break;case 24:this.h=new W(27,[p[m-2],p[m]]);break;case 25:this.h=new W(28,[p[m-4],p[m-2],p[m]]);break;case 26:this.h=new W(1,[void 0,p[m]],p[m-1]);break;case 27:this.h=new W(1,[p[m-3],p[m]],p[m-1]);break;case 28:this.h=new W(1,[p[m-5],p[m-1]],p[m-3]);break;case 29:this.h=new W(29,
[void 0,p[m]]);break;case 30:var t=new W(6,null,[p[m-2]]);this.h=new W(29,[t,p[m]]);break;case 31:this.h=new W(29,[p[m-3],p[m]]);break;case 32:this.h=new W(6,null,[p[m-2],p[m]]);break;case 33:this.h=p[m-2];this.h.value.push(p[m]);break;case 34:this.h=new W(2,[]);break;case 35:this.h=new W(2,[p[m-1]]);break;case 36:this.h=new W(3,[p[m-1],p[m]]);break;case 37:this.h=new W(4,null,p[m]);break;case 38:this.h=new W(4,[p[m-1]]);break;case 39:this.h=new W(5,null,p[m]);break;case 40:case 41:case 42:case 60:this.h=
p[m];break;case 43:p=a.substr(1,b-2);this.h=new W(6,null,p);break;case 44:this.h=new W(6,null,Number(a));break;case 45:this.h=new W(6,null,!0);break;case 46:this.h=new W(6,null,!1);break;case 47:this.h=new W(6,null,null);break;case 48:this.h=new W(7,[]);break;case 49:this.h=new W(7,[p[m-1]]);break;case 50:this.h=new W(7,[p[m-2]]);break;case 51:this.h=new W(8,[p[m]]);break;case 52:case 57:this.h=p[m-2];this.h.args.push(p[m]);break;case 53:this.h=new W(9,[]);break;case 54:this.h=new W(9,[p[m-1]]);break;
case 55:this.h=new W(9,[p[m-2]]);break;case 56:this.h=new W(10,[p[m]]);break;case 58:this.h=new W(11,[p[m-2],p[m]]);break;case 59:this.h=new W(6,null,p[m]);break;case 61:this.h=p[m-1]}},table:[{3:1,4:2,5:[1,3],6:4,7:5,8:6,9:b,11:8,12:9,13:d,14:e,15:f,29:k,38:l,40:14,41:15,42:16,43:h,44:g,45:n,46:r,47:q,48:u},{1:[3]},{5:[1,24],14:C,15:A,16:t,17:E,18:z,19:I,20:D,21:K,22:G,23:L,24:J,25:M,26:P,27:Q,31:w,37:40,38:x},{1:[2,2]},a(y,[2,3]),a(y,[2,4]),a(y,[2,5]),{4:42,6:4,7:5,8:6,9:b,11:8,12:9,13:d,14:e,15:f,
29:k,38:l,40:14,41:15,42:16,43:h,44:g,45:n,46:r,47:q,48:u},a(y,[2,7]),a(y,[2,8]),{4:43,6:4,7:5,8:6,9:b,11:8,12:9,13:d,14:e,15:f,29:k,38:l,40:14,41:15,42:16,43:h,44:g,45:n,46:r,47:q,48:u},{4:44,6:4,7:5,8:6,9:b,11:8,12:9,13:d,14:e,15:f,29:k,38:l,40:14,41:15,42:16,43:h,44:g,45:n,46:r,47:q,48:u},{4:45,6:4,7:5,8:6,9:b,11:8,12:9,13:d,14:e,15:f,29:k,38:l,40:14,41:15,42:16,43:h,44:g,45:n,46:r,47:q,48:u},a(y,ja,{30:46,9:ka}),a(y,[2,40]),a(y,[2,41]),a(y,[2,42]),a(y,[2,43]),a(y,[2,44]),a(y,[2,45]),a(y,[2,46]),
a(y,[2,47]),{29:Ca,38:ga,40:53,43:h,44:g,45:n,46:r,47:q,49:[1,48],50:49,51:50,52:51},{4:57,6:4,7:5,8:6,9:b,11:8,12:9,13:d,14:e,15:f,29:k,36:56,38:l,39:[1,55],40:14,41:15,42:16,43:h,44:g,45:n,46:r,47:q,48:u},{1:[2,1]},{4:58,6:4,7:5,8:6,9:b,11:8,12:9,13:d,14:e,15:f,29:k,38:l,40:14,41:15,42:16,43:h,44:g,45:n,46:r,47:q,48:u},{4:59,6:4,7:5,8:6,9:b,11:8,12:9,13:d,14:e,15:f,29:k,38:l,40:14,41:15,42:16,43:h,44:g,45:n,46:r,47:q,48:u},{4:60,6:4,7:5,8:6,9:b,11:8,12:9,13:d,14:e,15:f,29:k,38:l,40:14,41:15,42:16,
43:h,44:g,45:n,46:r,47:q,48:u},{4:61,6:4,7:5,8:6,9:b,11:8,12:9,13:d,14:e,15:f,29:k,38:l,40:14,41:15,42:16,43:h,44:g,45:n,46:r,47:q,48:u},{4:62,6:4,7:5,8:6,9:b,11:8,12:9,13:d,14:e,15:f,29:k,38:l,40:14,41:15,42:16,43:h,44:g,45:n,46:r,47:q,48:u},{4:63,6:4,7:5,8:6,9:b,11:8,12:9,13:d,14:e,15:f,29:k,38:l,40:14,41:15,42:16,43:h,44:g,45:n,46:r,47:q,48:u},{4:64,6:4,7:5,8:6,9:b,11:8,12:9,13:d,14:e,15:f,29:k,38:l,40:14,41:15,42:16,43:h,44:g,45:n,46:r,47:q,48:u},{4:65,6:4,7:5,8:6,9:b,11:8,12:9,13:d,14:e,15:f,
29:k,38:l,40:14,41:15,42:16,43:h,44:g,45:n,46:r,47:q,48:u},{4:66,6:4,7:5,8:6,9:b,11:8,12:9,13:d,14:e,15:f,29:k,38:l,40:14,41:15,42:16,43:h,44:g,45:n,46:r,47:q,48:u},{4:67,6:4,7:5,8:6,9:b,11:8,12:9,13:d,14:e,15:f,29:k,38:l,40:14,41:15,42:16,43:h,44:g,45:n,46:r,47:q,48:u},{4:68,6:4,7:5,8:6,9:b,11:8,12:9,13:d,14:e,15:f,29:k,38:l,40:14,41:15,42:16,43:h,44:g,45:n,46:r,47:q,48:u},{4:69,6:4,7:5,8:6,9:b,11:8,12:9,13:d,14:e,15:f,29:k,38:l,40:14,41:15,42:16,43:h,44:g,45:n,46:r,47:q,48:u},{4:70,6:4,7:5,8:6,
9:b,11:8,12:9,13:d,14:e,15:f,29:k,38:l,40:14,41:15,42:16,43:h,44:g,45:n,46:r,47:q,48:u},{4:71,6:4,7:5,8:6,9:b,11:8,12:9,13:d,14:e,15:f,29:k,38:l,40:14,41:15,42:16,43:h,44:g,45:n,46:r,47:q,48:u},{29:[1,72]},a(y,[2,36]),{4:73,6:4,7:5,8:6,9:b,11:8,12:9,13:d,14:e,15:f,29:k,38:l,40:14,41:15,42:16,43:h,44:g,45:n,46:r,47:q,48:u},{10:[1,74],14:C,15:A,16:t,17:E,18:z,19:I,20:D,21:K,22:G,23:L,24:J,25:M,26:P,27:Q,31:w,37:40,38:x},a(X,[2,9],{37:40,31:w,38:x}),a(X,[2,10],{37:40,31:w,38:x}),a(X,[2,11],{37:40,31:w,
38:x}),a(y,[2,26]),{4:57,6:4,7:5,8:6,9:b,10:Da,11:8,12:9,13:d,14:e,15:f,29:k,36:76,38:l,40:14,41:15,42:16,43:h,44:g,45:n,46:r,47:q,48:u},a(y,[2,53]),{35:[1,78],49:[1,77]},a(la,[2,56]),{28:[1,79]},{28:[2,59]},{28:[2,60]},{4:80,6:4,7:5,8:6,9:b,11:8,12:9,13:d,14:e,15:f,29:k,38:l,40:14,41:15,42:16,43:h,44:g,45:n,46:r,47:q,48:u},a(y,[2,48]),{35:[1,82],39:[1,81]},a(Ea,[2,51],{37:40,14:C,15:A,16:t,17:E,18:z,19:I,20:D,21:K,22:G,23:L,24:J,25:M,26:P,27:Q,31:w,38:x}),a(Fa,[2,12],{37:40,16:t,17:E,18:z,31:w,38:x}),
a(Fa,[2,13],{37:40,16:t,17:E,18:z,31:w,38:x}),a(X,[2,14],{37:40,31:w,38:x}),a(X,[2,15],{37:40,31:w,38:x}),a(X,[2,16],{37:40,31:w,38:x}),a([5,10,19,20,27,28,35,39,49],[2,17],{37:40,14:C,15:A,16:t,17:E,18:z,21:K,22:G,23:L,24:J,25:M,26:P,31:w,38:x}),a([5,10,20,27,28,35,39,49],[2,18],{37:40,14:C,15:A,16:t,17:E,18:z,19:I,21:K,22:G,23:L,24:J,25:M,26:P,31:w,38:x}),a(aa,[2,19],{37:40,14:C,15:A,16:t,17:E,18:z,31:w,38:x}),a(aa,[2,20],{37:40,14:C,15:A,16:t,17:E,18:z,31:w,38:x}),a(aa,[2,21],{37:40,14:C,15:A,
16:t,17:E,18:z,31:w,38:x}),a(aa,[2,22],{37:40,14:C,15:A,16:t,17:E,18:z,31:w,38:x}),a(ma,[2,23],{37:40,14:C,15:A,16:t,17:E,18:z,21:K,22:G,23:L,24:J,31:w,38:x}),a(ma,[2,24],{37:40,14:C,15:A,16:t,17:E,18:z,21:K,22:G,23:L,24:J,31:w,38:x}),{14:C,15:A,16:t,17:E,18:z,19:I,20:D,21:K,22:G,23:L,24:J,25:M,26:P,27:Q,28:[1,83],31:w,37:40,38:x},a(y,[2,37],{30:84,9:[1,85]}),{14:C,15:A,16:t,17:E,18:z,19:I,20:D,21:K,22:G,23:L,24:J,25:M,26:P,27:Q,31:w,37:40,38:x,39:[1,86]},a(y,[2,6]),a(y,[2,34]),{10:[1,87],35:[1,88]},
a(y,[2,54]),{29:Ca,38:ga,40:53,43:h,44:g,45:n,46:r,47:q,49:[1,89],51:90,52:51},{4:91,6:4,7:5,8:6,9:b,11:8,12:9,13:d,14:e,15:f,29:k,38:l,40:14,41:15,42:16,43:h,44:g,45:n,46:r,47:q,48:u},{14:C,15:A,16:t,17:E,18:z,19:I,20:D,21:K,22:G,23:L,24:J,25:M,26:P,27:Q,31:w,37:40,38:x,39:[1,92]},a(y,[2,49]),{4:94,6:4,7:5,8:6,9:b,11:8,12:9,13:d,14:e,15:f,29:k,38:l,39:[1,93],40:14,41:15,42:16,43:h,44:g,45:n,46:r,47:q,48:u},{4:95,6:4,7:5,8:6,9:b,11:8,12:9,13:d,14:e,15:f,29:k,38:l,40:14,41:15,42:16,43:h,44:g,45:n,
46:r,47:q,48:u},a(y,[2,27]),{4:57,6:4,7:5,8:6,9:[1,97],10:Da,11:8,12:9,13:d,14:e,15:f,29:[1,98],32:96,36:76,38:l,40:14,41:15,42:16,43:h,44:g,45:n,46:r,47:q,48:u},a(y,[2,38]),a(y,[2,35]),{4:94,6:4,7:5,8:6,9:b,11:8,12:9,13:d,14:e,15:f,29:k,38:l,40:14,41:15,42:16,43:h,44:g,45:n,46:r,47:q,48:u},a(y,[2,55]),a(la,[2,57]),a(la,[2,58],{37:40,14:C,15:A,16:t,17:E,18:z,19:I,20:D,21:K,22:G,23:L,24:J,25:M,26:P,27:Q,31:w,38:x}),{28:[2,61]},a(y,[2,50]),a(Ea,[2,52],{37:40,14:C,15:A,16:t,17:E,18:z,19:I,20:D,21:K,
22:G,23:L,24:J,25:M,26:P,27:Q,31:w,38:x}),a([5,10,28,35,39,49],[2,25],{37:40,14:C,15:A,16:t,17:E,18:z,19:I,20:D,21:K,22:G,23:L,24:J,25:M,26:P,27:Q,31:w,38:x}),{10:[1,99]},{4:42,6:4,7:5,8:6,9:b,10:[1,100],11:8,12:9,13:d,14:e,15:f,29:[1,102],34:101,38:l,40:14,41:15,42:16,43:h,44:g,45:n,46:r,47:q,48:u},a([10,14,15,16,17,18,19,20,21,22,23,24,25,26,27,31,35,38],ja,{30:46,9:ka,33:[1,103]}),a(y,[2,28]),{33:[1,104]},{10:[1,105],35:[1,106]},a([10,14,15,16,17,18,19,20,21,22,23,24,25,26,27,31,38],ja,{30:46,
9:ka,35:[1,107]}),{4:108,6:4,7:5,8:6,9:b,11:8,12:9,13:d,14:e,15:f,29:k,38:l,40:14,41:15,42:16,43:h,44:g,45:n,46:r,47:q,48:u},{4:109,6:4,7:5,8:6,9:b,11:8,12:9,13:d,14:e,15:f,29:k,38:l,40:14,41:15,42:16,43:h,44:g,45:n,46:r,47:q,48:u},{33:[1,110]},{29:[1,111]},{29:[1,112]},{10:[2,30],14:C,15:A,16:t,17:E,18:z,19:I,20:D,21:K,22:G,23:L,24:J,25:M,26:P,27:Q,31:w,37:40,38:x},{10:[2,29],14:C,15:A,16:t,17:E,18:z,19:I,20:D,21:K,22:G,23:L,24:J,25:M,26:P,27:Q,31:w,37:40,38:x},{4:113,6:4,7:5,8:6,9:b,11:8,12:9,13:d,
14:e,15:f,29:k,38:l,40:14,41:15,42:16,43:h,44:g,45:n,46:r,47:q,48:u},a(Ga,[2,33]),a(Ga,[2,32]),{10:[2,31],14:C,15:A,16:t,17:E,18:z,19:I,20:D,21:K,22:G,23:L,24:J,25:M,26:P,27:Q,31:w,37:40,38:x}],defaultActions:{3:[2,2],24:[2,1],52:[2,59],53:[2,60],92:[2,61]},parseError:function Cb(a,b){if(b.recoverable)this.trace(a);else throw a=Error(a),a.hash=b,a;},parse:function N(a){function b(a){d.length-=2*a;m.length-=a;t.length-=a}var c=this,d=[0],e=[],m=[null],t=[],f=this.table,h="",k=0,g=0,l=0,E=2,n=1,z=t.slice.call(arguments,
1),q=Object.create(this.lexer),u={yy:{}},r;for(r in this.yy)Object.prototype.hasOwnProperty.call(this.yy,r)&&(u.yy[r]=this.yy[r]);q.setInput(a,u.yy);u.yy.lexer=q;u.yy.parser=this;"undefined"==typeof q.yylloc&&(q.yylloc={});var I=q.yylloc;t.push(I);var K=q.options&&q.options.ranges;this.parseError="function"===typeof u.yy.parseError?u.yy.parseError:Object.getPrototypeOf(this).parseError;var C=function(){var a;a=q.lex()||n;"number"!==typeof a&&(a=c.va[a]||a);return a};for(var D,y,w,x={},A,G,L,J;;){r=
d[d.length-1];if(this.defaultActions[r])w=this.defaultActions[r];else{if(null===D||"undefined"==typeof D)D=C();w=f[r]&&f[r][D]}if("undefined"===typeof w||!w.length||!w[0]){var M="";J=[];for(A in f[r])this.S[A]&&A>E&&J.push("'"+this.S[A]+"'");M=q.showPosition?"Parse error on line "+(k+1)+":\n"+q.showPosition()+"\nExpecting "+J.join(", ")+", got '"+(this.S[D]||D)+"'":"Parse error on line "+(k+1)+": Unexpected "+(D==n?"end of input":"'"+(this.S[D]||D)+"'");this.parseError(M,{text:q.match,token:this.S[D]||
D,line:q.yylineno,loc:I,expected:J})}if(w[0]instanceof Array&&1<w.length)throw Error("Parse Error: multiple actions possible at state: "+r+", token: "+D);switch(w[0]){case 1:d.push(D);m.push(q.yytext);t.push(q.yylloc);d.push(w[1]);D=null;y?(D=y,y=null):(g=q.yyleng,h=q.yytext,k=q.yylineno,I=q.yylloc,0<l&&l--);break;case 2:G=this.ia[w[1]][1];x.h=m[m.length-G];x.$={first_line:t[t.length-(G||1)].first_line,last_line:t[t.length-1].last_line,first_column:t[t.length-(G||1)].first_column,last_column:t[t.length-
1].last_column};K&&(x.$.range=[t[t.length-(G||1)].range[0],t[t.length-1].range[1]]);r=this.performAction.apply(x,[h,g,k,u.yy,w[1],m,t].concat(z));if("undefined"!==typeof r)return r;G&&(d=d.slice(0,-2*G),m=m.slice(0,-1*G),t=t.slice(0,-1*G));d.push(this.ia[w[1]][0]);m.push(x.h);t.push(x.$);L=f[d[d.length-2]][d[d.length-1]];d.push(L);break;case 3:return!0}}}},$a=function(){return{EOF:1,parseError:function(a,b){if(this.yy.parser)this.yy.parser.parseError(a,b);else throw Error(a);},setInput:function(a,
b){this.yy=b||this.yy||{};this._input=a;this._more=this._backtrack=this.done=!1;this.yylineno=this.yyleng=0;this.yytext=this.matched=this.match="";this.conditionStack=["INITIAL"];this.yylloc={first_line:1,first_column:0,last_line:1,last_column:0};this.options.ranges&&(this.yylloc.range=[0,0]);this.offset=0;return this},input:function(){var a=this._input[0];this.yytext+=a;this.yyleng++;this.offset++;this.match+=a;this.matched+=a;var b=a.match(/(?:\r\n?|\n).*/g);b?(this.yylineno++,this.yylloc.last_line++):
this.yylloc.last_column++;this.options.ranges&&this.yylloc.range[1]++;this._input=this._input.slice(1);return a},unput:function(a){var b=a.length,c=a.split(/(?:\r\n?|\n)/g);this._input=a+this._input;this.yytext=this.yytext.substr(0,this.yytext.length-b);this.offset-=b;var d=this.match.split(/(?:\r\n?|\n)/g);this.match=this.match.substr(0,this.match.length-1);this.matched=this.matched.substr(0,this.matched.length-1);c.length-1&&(this.yylineno-=c.length-1);a=this.yylloc.range;this.yylloc={first_line:this.yylloc.first_line,
last_line:this.yylineno+1,first_column:this.yylloc.first_column,last_column:c?(c.length===d.length?this.yylloc.first_column:0)+d[d.length-c.length].length-c[0].length:this.yylloc.first_column-b};this.options.ranges&&(this.yylloc.range=[a[0],a[0]+this.yyleng-b]);this.yyleng=this.yytext.length;return this},more:function(){this._more=!0;return this},reject:function(){if(this.options.backtrack_lexer)this._backtrack=!0;else return this.parseError("Lexical error on line "+(this.yylineno+1)+". You can only invoke reject() in the lexer when the lexer is of the backtracking persuasion (options.backtrack_lexer = true).\n"+
this.showPosition(),{text:"",token:null,line:this.yylineno});return this},less:function(a){this.unput(this.match.slice(a))},pastInput:function(){var a=this.matched.substr(0,this.matched.length-this.match.length);return(20<a.length?"...":"")+a.substr(-20).replace(/\n/g,"")},upcomingInput:function(){var a=this.match;20>a.length&&(a+=this._input.substr(0,20-a.length));return(a.substr(0,20)+(20<a.length?"...":"")).replace(/\n/g,"")},showPosition:function(){var a=this.pastInput(),b=Array(a.length+1).join("-");
return a+this.upcomingInput()+"\n"+b+"^"},test_match:function(a,b){var c,d;this.options.backtrack_lexer&&(d={yylineno:this.yylineno,yylloc:{first_line:this.yylloc.first_line,last_line:this.last_line,first_column:this.yylloc.first_column,last_column:this.yylloc.last_column},yytext:this.yytext,match:this.match,matches:this.matches,matched:this.matched,yyleng:this.yyleng,offset:this.offset,_more:this._more,_input:this._input,yy:this.yy,conditionStack:this.conditionStack.slice(0),done:this.done},this.options.ranges&&
(d.yylloc.range=this.yylloc.range.slice(0)));if(c=a[0].match(/(?:\r\n?|\n).*/g))this.yylineno+=c.length;this.yylloc={first_line:this.yylloc.last_line,last_line:this.yylineno+1,first_column:this.yylloc.last_column,last_column:c?c[c.length-1].length-c[c.length-1].match(/\r?\n?/)[0].length:this.yylloc.last_column+a[0].length};this.yytext+=a[0];this.match+=a[0];this.matches=a;this.yyleng=this.yytext.length;this.options.ranges&&(this.yylloc.range=[this.offset,this.offset+=this.yyleng]);this._backtrack=
this._more=!1;this._input=this._input.slice(a[0].length);this.matched+=a[0];a=this.performAction.call(this,this.yy,this,b,this.conditionStack[this.conditionStack.length-1]);this.done&&this._input&&(this.done=!1);if(a)return a;if(this._backtrack)for(var e in d)this[e]=d[e];return!1},next:function(){if(this.done)return this.EOF;this._input||(this.done=!0);var a,b,c;this._more||(this.match=this.yytext="");for(var d=this._currentRules(),e=0;e<d.length;e++)if((b=this._input.match(this.rules[d[e]]))&&(!a||
b[0].length>a[0].length))if(a=b,c=e,this.options.backtrack_lexer){a=this.test_match(b,d[e]);if(!1!==a)return a;if(this._backtrack)a=!1;else return!1}else if(!this.options.flex)break;return a?(a=this.test_match(a,d[c]),!1!==a?a:!1):""===this._input?this.EOF:this.parseError("Lexical error on line "+(this.yylineno+1)+". Unrecognized text.\n"+this.showPosition(),{text:"",token:null,line:this.yylineno})},lex:function(){var a=this.next();return a?a:this.lex()},begin:function(a){this.conditionStack.push(a)},
popState:function m(){return 0<this.conditionStack.length-1?this.conditionStack.pop():this.conditionStack[0]},_currentRules:function Y(){return this.conditionStack.length&&this.conditionStack[this.conditionStack.length-1]?this.conditions[this.conditionStack[this.conditionStack.length-1]].rules:this.conditions.INITIAL.rules},topState:function Ya(a){a=this.conditionStack.length-1-Math.abs(a||0);return 0<=a?this.conditionStack[a]:"INITIAL"},pushState:function p(a){this.begin(a)},stateStackSize:function Za(){return this.conditionStack.length},
options:{},performAction:function(a,b,c,d){var e=d;switch(c){case 1:return 47;case 2:return 45;case 3:return 46;case 4:return 44;case 5:return 29;case 6:return 43;case 7:return 43;case 8:return 33;case 9:return 15;case 10:return 14;case 11:return 16;case 12:return 17;case 13:return 19;case 14:return 20;case 15:return 25;case 16:return 26;case 17:return 21;case 18:return 22;case 19:return 23;case 20:return 24;case 21:return 13;case 22:return 27;case 23:return 28;case 24:return 18;case 25:return 38;
case 26:return 39;case 27:return 48;case 28:return 49;case 29:return 9;case 30:return 10;case 31:return 35;case 32:return 31;case 33:return"INVALID";case 34:return 5}},rules:[/^(?:\s+)/,/^(?:null\b)/,/^(?:true\b)/,/^(?:false\b)/,/^(?:[0-9]+(\.[0-9]+)?\b)/,/^(?:[a-zA-Z_][a-zA-Z0-9_]*)/,/^(?:'[^\']*')/,/^(?:"[^\"]*")/,/^(?:=>)/,/^(?:\+)/,/^(?:-)/,/^(?:\*)/,/^(?:\/)/,/^(?:&&)/,/^(?:\|\|)/,/^(?:!=)/,/^(?:==)/,/^(?:<=)/,/^(?:<)/,/^(?:>=)/,/^(?:>)/,/^(?:!)/,/^(?:\?)/,/^(?::)/,/^(?:%)/,/^(?:\[)/,/^(?:\])/,
/^(?:\{)/,/^(?:\})/,/^(?:\()/,/^(?:\))/,/^(?:,)/,/^(?:\.)/,/^(?:.)/,/^(?:$)/],conditions:{INITIAL:{rules:[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34],inclusive:!0}}}}();na.lexer=$a;c.prototype=na;na.Parser=c;return new c})();function Xb(a){var c=a.match(/\s*(?:[\S]*)(?:\s+(?:-?(?:\d+(?:\.(?:\d+)?)?|\.\d+)[a-zA-Z]))?(?:\s*,)?/g);F().assert(0<c.length,"srcset has to have at least one source: %s",void 0);var b=[];for(a=0;a<c.length;a++){var d=c[a].trim();","==d.substr(-1)&&(d=d.substr(0,d.length-1).trim());var e=d.split(/\s+/,2);if(0!=e.length&&(1!=e.length||e[0])&&(2!=e.length||e[0]||e[1])){var f=e[0];if(1==e.length||2==e.length&&!e[1])b.push({url:f,width:void 0,dpr:1});else{var k=e[1].toLowerCase(),l=k.substring(k.length-
1);"w"==l?b.push({url:f,width:parseFloat(k),dpr:void 0}):"x"==l&&b.push({url:f,width:void 0,dpr:parseFloat(k)})}}}return new Yb(b)}
function Yb(a){F().assert(0<a.length,"Srcset must have at least one source");this.o=a;var c=!1,b=!1;for(a=0;a<this.o.length;a++){var d=this.o[a];F().assert((d.width||d.dpr)&&(!d.width||!d.dpr),"Either dpr or width must be specified");c=c||!!d.width;b=b||!!d.dpr}F().assert(!c||!b,"Srcset cannot have both width and dpr sources");c?this.o.sort(Zb):this.o.sort($b);this.Aa=c;this.pa=b}
Yb.prototype.select=function(a,c){var b=-1;if(this.Aa)a:{for(var b=-Infinity,d=this.o.length-1;0<=d;d--){var e=this.o[d].width/c;if(e>=a){b=1.1*(a-b)<e-a&&1.2>=a/b?d+1:d;break a}b=e}b=0}else if(this.pa){a=-1;b=1E6;for(d=0;d<this.o.length;d++)e=Math.abs((this.o[d].dpr||1)-c),e<b&&(b=e,a=d);b=a}return-1!=b?this.o[b]:this.getLast()};Yb.prototype.getLast=function(){return this.o[this.o.length-1]};Yb.prototype.getSources=function(){return this.o};
Yb.prototype.stringify=function(){for(var a=[],c=0;c<this.o.length;c++){var b=this.o[c];b.width?a.push(b.url+" "+b.width+"w"):b.dpr?a.push(b.url+" "+b.dpr+"x"):a.push(""+b.url)}return a.join(", ")};function Zb(a,c){F().assert(a.width!=c.width,"Duplicate width: %s",a.width);return c.width-a.width}function $b(a,c){F().assert(a.dpr!=c.dpr,"Duplicate dpr: %s",a.dpr);return c.dpr-a.dpr};var ac={"class":{blacklistedValueRegex:"(^|\\W)i-amphtml-"},hidden:null,text:null},bc={width:null,height:null},cc={"AMP-BRIGHTCOVE":{"data-account":null,"data-embed":null,"data-player":null,"data-player-id":null,"data-playlist-id":null,"data-video-id":null},"AMP-CAROUSEL":{slide:null},"AMP-IFRAME":{src:null},"AMP-IMG":{alt:null,attribution:null,src:{allowedProtocols:{data:!0,http:!0,https:!0}},srcset:{alternativeName:"src"}},"AMP-LIST":{src:{allowedProtocols:{https:!0}},state:null},"AMP-SELECTOR":{disabled:null,
selected:null},"AMP-STATE":{src:{allowedProtocols:{https:!0}}},"AMP-VIDEO":{alt:null,attribution:null,controls:null,loop:null,poster:null,preload:null,src:{allowedProtocols:{https:!0}}},"AMP-YOUTUBE":{"data-videoid":null},A:{href:{allowedProtocols:{ftp:!0,http:!0,https:!0,mailto:!0,"fb-messenger":!0,intent:!0,skype:!0,sms:!0,snapchat:!0,tel:!0,tg:!0,threema:!0,twitter:!0,viber:!0,whatsapp:!0}}},BUTTON:{disabled:null,type:null,value:null},FIELDSET:{disabled:null},INPUT:{accept:null,accesskey:null,
autocomplete:null,checked:null,disabled:null,height:null,inputmode:null,max:null,maxlength:null,min:null,minlength:null,multiple:null,pattern:null,placeholder:null,readonly:null,required:null,selectiondirection:null,size:null,spellcheck:null,step:null,type:{blacklistedValueRegex:"(^|\\s)(button|file|image|password|)(\\s|$)"},value:null,width:null},OPTION:{disabled:null,label:null,selected:null,value:null},OPTGROUP:{disabled:null,label:null},SELECT:{autofocus:null,disabled:null,multiple:null,required:null,
size:null},SOURCE:{src:{allowedProtocols:{https:!0}},type:null},TRACK:{label:null,src:{allowedProtocols:{https:!0}},srclang:null},TEXTAREA:{autocomplete:null,autofocus:null,cols:null,disabled:null,maxlength:null,minlength:null,placeholder:null,readonly:null,required:null,rows:null,selectiondirection:null,selectionend:null,selectionstart:null,spellcheck:null,wrap:null}},dc={src:!0,srcset:!0,href:!0};function ec(){}ec.prototype.canBind=function(a,c){return void 0!==fc(a,c)};
ec.prototype.isResultValid=function(a,c,b){var d=fc(a,c);d&&d.alternativeName&&(d=fc(a,d.alternativeName));if(void 0===d)return!1;if(null===d)return!0;if(b&&wa(dc,c)){var e;if("srcset"===c){var f;try{f=Xb(b)}catch(h){return F().error("amp-bind","Failed to parse srcset: ",h),!1}e=f.getSources().map(function(a){return a.url})}else e=[b];for(a=0;a<e.length;a++)if(!gc(e[a],d))return!1}var k=d.blacklistedValueRegex;if(b&&k){var l=new RegExp(k,"i");if(l.test(b))return!1}return!0};
function gc(a,c){var b=c.allowedProtocols;return b&&a&&(a=/^([^:\/?#.]+):[\s\S]*$/.exec(a),null!==a&&(a=a[1].toLowerCase().trim(),!b.hasOwnProperty(a)))?!1:!0}function fc(a,c){if(R(c,"aria-"))return null;var b=wa(ac,c);if(void 0!==b)return b;var d=wa(bc,c);if(R(a,"AMP-")&&void 0!==d)return d;var e=wa(cc,a);if(e)return e[c]};function hc(){this.D=[]}hc.prototype.peek=function(){var a=this.D.length;return a?this.D[a-1].item:null};hc.prototype.enqueue=function(a,c){if(isNaN(c))throw Error("Priority must not be NaN.");for(var b=c,d=-1,e=0,f=this.D.length;e<=f;){d=Math.floor((e+f)/2);if(d===this.D.length)break;if(this.D[d].priority<b)e=d+1;else if(0<d&&this.D[d-1].priority>=b)f=d-1;else break}this.D.splice(d,0,{item:a,priority:c})};hc.prototype.dequeue=function(){return this.D.length?this.D.pop().item:null};
ca.Object.defineProperties(hc.prototype,{length:{configurable:!0,enumerable:!0,get:function(){return this.D.length}}});var ic=/nochunking=1/.test(self.location.hash),jc=Promise.resolve();function kc(a,c){if(ic)jc.then(c);else{var b=lc,d=cb(a),e=db(d);Xa(e,d,"chunk",b);T(a,"chunk").run(c,10)}}function mc(a){this.state="not_run";this.W=a}function nc(a,c){if("run"!=a.state){a.state="run";try{a.W(c)}catch(b){throw a.ga(b),b;}}}mc.prototype.O=function(){return this.W.displayName||this.W.name};mc.prototype.ga=function(){};mc.prototype.fa=function(){return!1};mc.prototype.ka=function(){return!0};
function oc(a,c,b){mc.call(this,a);var d=this;this.w=c;this.F=null;b.then(function(a){d.F=a;d.F.isVisible()&&nc(d,null);d.F.onVisibilityChanged(function(){d.F.isVisible()&&nc(d,null)})})}ba(oc,mc);oc.prototype.ga=function(){Fb(self.document)};oc.prototype.fa=function(){return this.F?this.F.isVisible():this.w.document.hidden?!1:!/visibilityState=(hidden|prerender)/.test(this.w.location.hash)};oc.prototype.ka=function(){return!!this.F};
function lc(a){var c=this;this.Ca=a;this.w=a.win;this.R=new hc;this.aa=this.ba.bind(this);this.za=fb(db(a),"viewer");this.w.addEventListener("message",function(a){"amp-macro-task"==a.data&&c.ba(null)})}lc.prototype.run=function(a,c){var b=new mc(a);pc(this,b,c)};lc.prototype.Ga=function(a){a=new oc(a,this.w,this.za);pc(this,a,Number.POSITIVE_INFINITY)};function pc(a,c,b){a.R.enqueue(c,b);jc.then(function(){qc(a)})}
function rc(a,c){for(var b=a.R.peek();b&&"not_run"!==b.state;)a.R.dequeue(),b=a.R.peek();b&&c&&a.R.dequeue();return b}lc.prototype.ba=function(a){var c=this,b=rc(this,!0);if(!b)return!1;var d=Date.now();nc(b,a);jc.then(function(){qc(c)});return!0};function sc(a){jc.then(function(){a.aa(null)})}function qc(a){var c=rc(a);c&&(c.fa()?sc(a):c.ka()&&a.w.requestIdleCallback?tc(a.w,a.aa):a.w.postMessage("amp-macro-task","*"))}
function tc(a,c){var b=15,d=2E3;function e(k){if(k.timeRemaining()<b){var l=d-(Date.now()-f);0>=l||k.didTimeout?c(k):a.requestIdleCallback(e,{timeout:l})}else c(k)}var f=Date.now();a.requestIdleCallback(e,{timeout:d})};function uc(a,c,b){var d="ww";a=c?a.protocol+"//"+a.host+"/dist":za;return b?a+"/rtv/"+B().rtvVersion+"/"+d+".js":a+"/"+d+".js"};function vc(a){var c=this;this.w=a;this.Ba=U(a,"xhr");var b=a.location,d=!1,e=!d,f=uc(b,d,e);this.Z=null;this.da=this.Ba.fetchText(f,{ampCors:!1}).then(function(a){return a.text()}).then(function(b){b=new a.Blob([b],{type:"text/javascript"});var d=a.URL.createObjectURL(b);c.Z=new a.Worker(d);c.Z.onmessage=c.ua.bind(c)});this.U={};this.na=0;this.la=[a]}
function wc(a,c,b,d){return a.da.then(function(){return new Promise(function(e,f){var k=a.na++;a.U[k]={method:c,resolve:e,reject:f};e=d||a.w;f=a.la.indexOf(e);e=0<=f?f:a.la.push(e)-1;a.Z.postMessage({method:c,args:b,scope:e,id:k})})})}vc.prototype.ua=function(a){var c=a.data;a=c.method;var b=c.returnValue,c=c.id,d=this.U[c];d?(d.resolve(b),delete this.U[c]):ua().error("web-worker","Received unexpected message ("+a+", "+c+") from worker.")};vc.prototype.hasPendingMessages=function(){return 0<Object.keys(this.U).length};
vc.prototype.Da=function(){return this.da};var xc=function(){function a(a){var b=(""+a).match(u);return b?new h(g(b[1]),g(b[2]),g(b[3]),g(b[4]),g(b[5]),g(b[6]),g(b[7])):null}function c(a,c,f,k,g,l,n){a=new h(d(a,C),d(c,C),b(f),0<k?k.toString():null,d(g,A),null,b(n));l&&("string"===typeof l?a.setRawQuery(l.replace(/[^?&=0-9A-Za-z_\-~.%]/g,e)):a.setAllParameters(l));return a}function b(a){return"string"==typeof a?encodeURIComponent(a):null}function d(a,b){return"string"==typeof a?encodeURI(a).replace(b,e):null}function e(a){a=a.charCodeAt(0);
return"%"+"0123456789ABCDEF".charAt(a>>4&15)+"0123456789ABCDEF".charAt(a&15)}function f(a){return a.replace(/(^|\/)\.(?:\/|$)/g,"$1").replace(/\/{2,}/g,"/")}function k(a){if(null===a)return null;a=f(a);for(var b=r,c;(c=a.replace(b,"$1"))!=a;a=c);return a}function l(a,b){var c=a.clone(),d=b.hasScheme();d?c.setRawScheme(b.getRawScheme()):d=b.hasCredentials();d?c.setRawCredentials(b.getRawCredentials()):d=b.hasDomain();d?c.setRawDomain(b.getRawDomain()):d=b.hasPort();var e=b.getRawPath(),f=k(e);if(d)c.setPort(b.getPort()),
f=f&&f.replace(q,"");else if(d=!!e){if(47!==f.charCodeAt(0))var t=k(c.getRawPath()||"").replace(q,""),h=t.lastIndexOf("/")+1,f=k((h?t.substring(0,h):"")+k(e)).replace(q,"")}else f=f&&f.replace(q,""),f!==e&&c.setRawPath(f);d?c.setRawPath(f):d=b.hasQuery();d?c.setRawQuery(b.getRawQuery()):d=b.hasFragment();d&&c.setRawFragment(b.getRawFragment());return c}function h(a,b,c,d,e,f,h){this.J=a;this.G=b;this.H=c;this.K=d;this.C=e;this.B=f;this.I=h;this.j=null}function g(a){return"string"==typeof a&&0<a.length?
a:null}var n=/(\/|^)(?:[^./][^/]*|\.{2,}(?:[^./][^/]*)|\.{3,}[^/]*)\/\.\.(?:\/|$)/,r=new RegExp(n),q=/^(?:\.\.\/)*(?:\.\.$)?/;h.prototype.toString=function(){var a=[];null!==this.J&&a.push(this.J,":");null!==this.H&&(a.push("//"),null!==this.G&&a.push(this.G,"@"),a.push(this.H),null!==this.K&&a.push(":",this.K.toString()));null!==this.C&&a.push(this.C);null!==this.B&&a.push("?",this.B);null!==this.I&&a.push("#",this.I);return a.join("")};h.prototype.clone=function(){return new h(this.J,this.G,this.H,
this.K,this.C,this.B,this.I)};h.prototype.getScheme=function(){return this.J&&decodeURIComponent(this.J).toLowerCase()};h.prototype.getRawScheme=function(){return this.J};h.prototype.setScheme=function(a){this.J=d(a,C);return this};h.prototype.setRawScheme=function(a){this.J=a?a:null;return this};h.prototype.hasScheme=function(){return null!==this.J};h.prototype.getCredentials=function(){return this.G&&decodeURIComponent(this.G)};h.prototype.getRawCredentials=function(){return this.G};h.prototype.setCredentials=
function(a){this.G=d(a,C);return this};h.prototype.setRawCredentials=function(a){this.G=a?a:null;return this};h.prototype.hasCredentials=function(){return null!==this.G};h.prototype.getDomain=function(){return this.H&&decodeURIComponent(this.H)};h.prototype.getRawDomain=function(){return this.H};h.prototype.setDomain=function(a){return this.setRawDomain(a&&encodeURIComponent(a))};h.prototype.setRawDomain=function(a){this.H=a?a:null;return this.setRawPath(this.C)};h.prototype.hasDomain=function(){return null!==
this.H};h.prototype.getPort=function(){return this.K&&decodeURIComponent(this.K)};h.prototype.setPort=function(a){if(a){a=Number(a);if(a!==(a&65535))throw Error("Bad port number "+a);this.K=""+a}else this.K=null;return this};h.prototype.hasPort=function(){return null!==this.K};h.prototype.getPath=function(){return this.C&&decodeURIComponent(this.C)};h.prototype.getRawPath=function(){return this.C};h.prototype.setPath=function(a){return this.setRawPath(d(a,A))};h.prototype.setRawPath=function(a){a?
(a=String(a),this.C=!this.H||/^\//.test(a)?a:"/"+a):this.C=null;return this};h.prototype.hasPath=function(){return null!==this.C};h.prototype.getQuery=function(){return this.B&&decodeURIComponent(this.B).replace(/\+/g," ")};h.prototype.getRawQuery=function(){return this.B};h.prototype.setQuery=function(a){this.j=null;this.B=b(a);return this};h.prototype.setRawQuery=function(a){this.j=null;this.B=a?a:null;return this};h.prototype.hasQuery=function(){return null!==this.B};h.prototype.setAllParameters=
function(a){if("object"===typeof a&&!(a instanceof Array)&&(a instanceof Object||"[object Array]"!==Object.prototype.toString.call(a))){var b=[],c=-1,d;for(d in a){var e=a[d];"string"===typeof e&&(b[++c]=d,b[++c]=e)}a=b}this.j=null;for(var f=[],h="",k=0;k<a.length;)d=a[k++],e=a[k++],f.push(h,encodeURIComponent(d.toString())),h="&",e&&f.push("=",encodeURIComponent(e.toString()));this.B=f.join("");return this};h.prototype.N=function(){if(!this.j){var a=this.B;if(a){for(var b=a.split(/[&\?]/),a=[],c=
-1,d=0;d<b.length;++d){var e=b[d].match(/^([^=]*)(?:=(.*))?$/);a[++c]=decodeURIComponent(e[1]).replace(/\+/g," ");a[++c]=decodeURIComponent(e[2]||"").replace(/\+/g," ")}this.j=a}else this.j=[]}};h.prototype.setParameterValues=function(a,b){"string"===typeof b&&(b=[b]);this.N();for(var c=0,d=this.j,e=[],f=0;f<d.length;f+=2)a===d[f]?c<b.length&&e.push(a,b[c++]):e.push(d[f],d[f+1]);for(;c<b.length;)e.push(a,b[c++]);this.setAllParameters(e);return this};h.prototype.removeParameter=function(a){return this.setParameterValues(a,
[])};h.prototype.getAllParameters=function(){this.N();return this.j.slice(0,this.j.length)};h.prototype.getParameterValues=function(a){this.N();for(var b=[],c=0;c<this.j.length;c+=2)a===this.j[c]&&b.push(this.j[c+1]);return b};h.prototype.getParameterMap=function(){this.N();for(var a={},b=0;b<this.j.length;b+=2){var c=this.j[b++],d=this.j[b++];c in a?a[c].push(d):a[c]=[d]}return a};h.prototype.getParameterValue=function(a){this.N();for(var b=0;b<this.j.length;b+=2)if(a===this.j[b])return this.j[b+
1];return null};h.prototype.getFragment=function(){return this.I&&decodeURIComponent(this.I)};h.prototype.getRawFragment=function(){return this.I};h.prototype.setFragment=function(a){this.I=a?encodeURIComponent(a):null;return this};h.prototype.setRawFragment=function(a){this.I=a?a:null;return this};h.prototype.hasFragment=function(){return null!==this.I};var u=/^(?:([^:/?#]+):)?(?:\/\/(?:([^/?#]*)@)?([^/?#:@]*)(?::([0-9]+))?)?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/,C=/[#\/\?@]/g,A=/[\#\?]/g;h.parse=a;
h.create=c;h.resolve=l;h.collapse_dots=k;h.utils={mimeTypeOf:function(b){var c=a(b);return/\.html$/.test(c.getPath())?"text/html":"application/javascript"},resolve:function(b,c){return b?l(a(b),a(c)).toString():""+c}};return h}(),Z={atype:{NONE:0,URI:1,URI_FRAGMENT:11,SCRIPT:2,STYLE:3,HTML:12,ID:4,IDREF:5,IDREFS:6,GLOBAL_NAME:7,LOCAL_NAME:8,CLASSES:9,FRAME_TARGET:10,MEDIA_QUERY:13}};Z.atype=Z.atype;
Z.ATTRIBS={"*::class":9,"*::dir":0,"*::draggable":0,"*::hidden":0,"*::id":4,"*::inert":0,"*::itemprop":0,"*::itemref":6,"*::itemscope":0,"*::lang":0,"*::onblur":2,"*::onchange":2,"*::onclick":2,"*::ondblclick":2,"*::onerror":2,"*::onfocus":2,"*::onkeydown":2,"*::onkeypress":2,"*::onkeyup":2,"*::onload":2,"*::onmousedown":2,"*::onmousemove":2,"*::onmouseout":2,"*::onmouseover":2,"*::onmouseup":2,"*::onreset":2,"*::onscroll":2,"*::onselect":2,"*::onsubmit":2,"*::ontouchcancel":2,"*::ontouchend":2,"*::ontouchenter":2,
"*::ontouchleave":2,"*::ontouchmove":2,"*::ontouchstart":2,"*::onunload":2,"*::spellcheck":0,"*::style":3,"*::tabindex":0,"*::title":0,"*::translate":0,"a::accesskey":0,"a::coords":0,"a::href":1,"a::hreflang":0,"a::name":7,"a::onblur":2,"a::onfocus":2,"a::shape":0,"a::target":10,"a::type":0,"area::accesskey":0,"area::alt":0,"area::coords":0,"area::href":1,"area::nohref":0,"area::onblur":2,"area::onfocus":2,"area::shape":0,"area::target":10,"audio::controls":0,"audio::loop":0,"audio::mediagroup":5,
"audio::muted":0,"audio::preload":0,"audio::src":1,"bdo::dir":0,"blockquote::cite":1,"br::clear":0,"button::accesskey":0,"button::disabled":0,"button::name":8,"button::onblur":2,"button::onfocus":2,"button::type":0,"button::value":0,"canvas::height":0,"canvas::width":0,"caption::align":0,"col::align":0,"col::char":0,"col::charoff":0,"col::span":0,"col::valign":0,"col::width":0,"colgroup::align":0,"colgroup::char":0,"colgroup::charoff":0,"colgroup::span":0,"colgroup::valign":0,"colgroup::width":0,
"command::checked":0,"command::command":5,"command::disabled":0,"command::icon":1,"command::label":0,"command::radiogroup":0,"command::type":0,"data::value":0,"del::cite":1,"del::datetime":0,"details::open":0,"dir::compact":0,"div::align":0,"dl::compact":0,"fieldset::disabled":0,"font::color":0,"font::face":0,"font::size":0,"form::accept":0,"form::action":1,"form::autocomplete":0,"form::enctype":0,"form::method":0,"form::name":7,"form::novalidate":0,"form::onreset":2,"form::onsubmit":2,"form::target":10,
"h1::align":0,"h2::align":0,"h3::align":0,"h4::align":0,"h5::align":0,"h6::align":0,"hr::align":0,"hr::noshade":0,"hr::size":0,"hr::width":0,"iframe::align":0,"iframe::frameborder":0,"iframe::height":0,"iframe::marginheight":0,"iframe::marginwidth":0,"iframe::width":0,"img::align":0,"img::alt":0,"img::border":0,"img::height":0,"img::hspace":0,"img::ismap":0,"img::name":7,"img::src":1,"img::usemap":11,"img::vspace":0,"img::width":0,"input::accept":0,"input::accesskey":0,"input::align":0,"input::alt":0,
"input::autocomplete":0,"input::checked":0,"input::disabled":0,"input::inputmode":0,"input::ismap":0,"input::list":5,"input::max":0,"input::maxlength":0,"input::min":0,"input::multiple":0,"input::name":8,"input::onblur":2,"input::onchange":2,"input::onfocus":2,"input::onselect":2,"input::pattern":0,"input::placeholder":0,"input::readonly":0,"input::required":0,"input::size":0,"input::src":1,"input::step":0,"input::type":0,"input::usemap":11,"input::value":0,"ins::cite":1,"ins::datetime":0,"label::accesskey":0,
"label::for":5,"label::onblur":2,"label::onfocus":2,"legend::accesskey":0,"legend::align":0,"li::type":0,"li::value":0,"map::name":7,"menu::compact":0,"menu::label":0,"menu::type":0,"meter::high":0,"meter::low":0,"meter::max":0,"meter::min":0,"meter::optimum":0,"meter::value":0,"ol::compact":0,"ol::reversed":0,"ol::start":0,"ol::type":0,"optgroup::disabled":0,"optgroup::label":0,"option::disabled":0,"option::label":0,"option::selected":0,"option::value":0,"output::for":6,"output::name":8,"p::align":0,
"pre::width":0,"progress::max":0,"progress::min":0,"progress::value":0,"q::cite":1,"select::autocomplete":0,"select::disabled":0,"select::multiple":0,"select::name":8,"select::onblur":2,"select::onchange":2,"select::onfocus":2,"select::required":0,"select::size":0,"source::type":0,"table::align":0,"table::bgcolor":0,"table::border":0,"table::cellpadding":0,"table::cellspacing":0,"table::frame":0,"table::rules":0,"table::summary":0,"table::width":0,"tbody::align":0,"tbody::char":0,"tbody::charoff":0,
"tbody::valign":0,"td::abbr":0,"td::align":0,"td::axis":0,"td::bgcolor":0,"td::char":0,"td::charoff":0,"td::colspan":0,"td::headers":6,"td::height":0,"td::nowrap":0,"td::rowspan":0,"td::scope":0,"td::valign":0,"td::width":0,"template::type":0,"textarea::accesskey":0,"textarea::autocomplete":0,"textarea::cols":0,"textarea::disabled":0,"textarea::inputmode":0,"textarea::name":8,"textarea::onblur":2,"textarea::onchange":2,"textarea::onfocus":2,"textarea::onselect":2,"textarea::placeholder":0,"textarea::readonly":0,
"textarea::required":0,"textarea::rows":0,"textarea::wrap":0,"tfoot::align":0,"tfoot::char":0,"tfoot::charoff":0,"tfoot::valign":0,"th::abbr":0,"th::align":0,"th::axis":0,"th::bgcolor":0,"th::char":0,"th::charoff":0,"th::colspan":0,"th::headers":6,"th::height":0,"th::nowrap":0,"th::rowspan":0,"th::scope":0,"th::valign":0,"th::width":0,"thead::align":0,"thead::char":0,"thead::charoff":0,"thead::valign":0,"tr::align":0,"tr::bgcolor":0,"tr::char":0,"tr::charoff":0,"tr::valign":0,"track::default":0,"track::kind":0,
"track::label":0,"track::srclang":0,"ul::compact":0,"ul::type":0,"video::controls":0,"video::height":0,"video::loop":0,"video::mediagroup":5,"video::muted":0,"video::poster":1,"video::preload":0,"video::src":1,"video::width":0};Z.ATTRIBS=Z.ATTRIBS;Z.eflags={OPTIONAL_ENDTAG:1,EMPTY:2,CDATA:4,RCDATA:8,UNSAFE:16,FOLDABLE:32,SCRIPT:64,STYLE:128,VIRTUALIZED:256};Z.eflags=Z.eflags;
Z.ELEMENTS={a:0,abbr:0,acronym:0,address:0,applet:272,area:2,article:0,aside:0,audio:0,b:0,base:274,basefont:274,bdi:0,bdo:0,big:0,blockquote:0,body:305,br:2,button:0,canvas:0,caption:0,center:0,cite:0,code:0,col:2,colgroup:1,command:2,data:0,datalist:0,dd:1,del:0,details:0,dfn:0,dialog:272,dir:0,div:0,dl:0,dt:1,em:0,fieldset:0,figcaption:0,figure:0,font:0,footer:0,form:0,frame:274,frameset:272,h1:0,h2:0,h3:0,h4:0,h5:0,h6:0,head:305,header:0,hgroup:0,hr:2,html:305,i:0,iframe:4,img:2,input:2,ins:0,
isindex:274,kbd:0,keygen:274,label:0,legend:0,li:1,link:274,map:0,mark:0,menu:0,meta:274,meter:0,nav:0,nobr:0,noembed:276,noframes:276,noscript:276,object:272,ol:0,optgroup:0,option:1,output:0,p:1,param:274,pre:0,progress:0,q:0,s:0,samp:0,script:84,section:0,select:0,small:0,source:2,span:0,strike:0,strong:0,style:148,sub:0,summary:0,sup:0,table:0,tbody:1,td:1,template:4,textarea:8,tfoot:1,th:1,thead:1,time:0,title:280,tr:1,track:2,tt:0,u:0,ul:0,"var":0,video:0,wbr:2};Z.ELEMENTS=Z.ELEMENTS;
Z.ELEMENT_DOM_INTERFACES={a:"HTMLAnchorElement",abbr:"HTMLElement",acronym:"HTMLElement",address:"HTMLElement",applet:"HTMLAppletElement",area:"HTMLAreaElement",article:"HTMLElement",aside:"HTMLElement",audio:"HTMLAudioElement",b:"HTMLElement",base:"HTMLBaseElement",basefont:"HTMLBaseFontElement",bdi:"HTMLElement",bdo:"HTMLElement",big:"HTMLElement",blockquote:"HTMLQuoteElement",body:"HTMLBodyElement",br:"HTMLBRElement",button:"HTMLButtonElement",canvas:"HTMLCanvasElement",caption:"HTMLTableCaptionElement",
center:"HTMLElement",cite:"HTMLElement",code:"HTMLElement",col:"HTMLTableColElement",colgroup:"HTMLTableColElement",command:"HTMLCommandElement",data:"HTMLElement",datalist:"HTMLDataListElement",dd:"HTMLElement",del:"HTMLModElement",details:"HTMLDetailsElement",dfn:"HTMLElement",dialog:"HTMLDialogElement",dir:"HTMLDirectoryElement",div:"HTMLDivElement",dl:"HTMLDListElement",dt:"HTMLElement",em:"HTMLElement",fieldset:"HTMLFieldSetElement",figcaption:"HTMLElement",figure:"HTMLElement",font:"HTMLFontElement",
footer:"HTMLElement",form:"HTMLFormElement",frame:"HTMLFrameElement",frameset:"HTMLFrameSetElement",h1:"HTMLHeadingElement",h2:"HTMLHeadingElement",h3:"HTMLHeadingElement",h4:"HTMLHeadingElement",h5:"HTMLHeadingElement",h6:"HTMLHeadingElement",head:"HTMLHeadElement",header:"HTMLElement",hgroup:"HTMLElement",hr:"HTMLHRElement",html:"HTMLHtmlElement",i:"HTMLElement",iframe:"HTMLIFrameElement",img:"HTMLImageElement",input:"HTMLInputElement",ins:"HTMLModElement",isindex:"HTMLUnknownElement",kbd:"HTMLElement",
keygen:"HTMLKeygenElement",label:"HTMLLabelElement",legend:"HTMLLegendElement",li:"HTMLLIElement",link:"HTMLLinkElement",map:"HTMLMapElement",mark:"HTMLElement",menu:"HTMLMenuElement",meta:"HTMLMetaElement",meter:"HTMLMeterElement",nav:"HTMLElement",nobr:"HTMLElement",noembed:"HTMLElement",noframes:"HTMLElement",noscript:"HTMLElement",object:"HTMLObjectElement",ol:"HTMLOListElement",optgroup:"HTMLOptGroupElement",option:"HTMLOptionElement",output:"HTMLOutputElement",p:"HTMLParagraphElement",param:"HTMLParamElement",
pre:"HTMLPreElement",progress:"HTMLProgressElement",q:"HTMLQuoteElement",s:"HTMLElement",samp:"HTMLElement",script:"HTMLScriptElement",section:"HTMLElement",select:"HTMLSelectElement",small:"HTMLElement",source:"HTMLSourceElement",span:"HTMLSpanElement",strike:"HTMLElement",strong:"HTMLElement",style:"HTMLStyleElement",sub:"HTMLElement",summary:"HTMLElement",sup:"HTMLElement",table:"HTMLTableElement",tbody:"HTMLTableSectionElement",td:"HTMLTableDataCellElement",template:"HTMLTemplateElement",textarea:"HTMLTextAreaElement",
tfoot:"HTMLTableSectionElement",th:"HTMLTableHeaderCellElement",thead:"HTMLTableSectionElement",time:"HTMLTimeElement",title:"HTMLTitleElement",tr:"HTMLTableRowElement",track:"HTMLTrackElement",tt:"HTMLElement",u:"HTMLElement",ul:"HTMLUListElement","var":"HTMLElement",video:"HTMLVideoElement",wbr:"HTMLElement"};Z.ELEMENT_DOM_INTERFACES=Z.ELEMENT_DOM_INTERFACES;Z.ueffects={NOT_LOADED:0,SAME_DOCUMENT:1,NEW_DOCUMENT:2};Z.ueffects=Z.ueffects;
Z.URIEFFECTS={"a::href":2,"area::href":2,"audio::src":1,"blockquote::cite":0,"command::icon":1,"del::cite":0,"form::action":2,"img::src":1,"input::src":1,"ins::cite":0,"q::cite":0,"video::poster":1,"video::src":1};Z.URIEFFECTS=Z.URIEFFECTS;Z.ltypes={UNSANDBOXED:2,SANDBOXED:1,DATA:0};Z.ltypes=Z.ltypes;
Z.LOADERTYPES={"a::href":2,"area::href":2,"audio::src":2,"blockquote::cite":2,"command::icon":1,"del::cite":2,"form::action":2,"img::src":1,"input::src":1,"ins::cite":2,"q::cite":2,"video::poster":1,"video::src":2};Z.LOADERTYPES=Z.LOADERTYPES;
(function(a){function c(a){if(y.hasOwnProperty(a))return y[a];var b=a.match(ja);return b?String.fromCharCode(parseInt(b[1],10)):(b=a.match(ka))?String.fromCharCode(parseInt(b[1],16)):ga&&Ca.test(a)?(ga.innerHTML="&"+a+";",b=ga.textContent,y[a]=b):"&"+a+";"}function b(a,b){return c(b)}function d(a){return a.replace(X,"")}function e(a){return a.replace(Da,b)}function f(a){return(""+a).replace(Ea,"&amp;").replace(aa,"&lt;").replace(ma,"&gt;").replace(Ga,"&#34;")}function k(a){return a.replace(Fa,"&amp;$1").replace(aa,
"&lt;").replace(ma,"&gt;")}function l(a){var b={cdata:a.cdata||a.cdata,comment:a.comment||a.comment,endDoc:a.endDoc||a.endDoc,endTag:a.endTag||a.endTag,pcdata:a.pcdata||a.pcdata,rcdata:a.rcdata||a.rcdata,startDoc:a.startDoc||a.startDoc,startTag:a.startTag||a.startTag};return function(a,c){var d=b,e=n(a);g(d,e,0,{noMoreGT:!1,noMoreEndComments:!1},c)}}function h(a,b,c,d,e){return function(){g(a,b,c,d,e)}}function g(b,c,d,e,f){try{b.startDoc&&0==d&&b.startDoc(f);for(var m,k,p,g=d,l=c.length;g<l;){var n=
c[g++],Y=c[g];switch(n){case "&":la.test(Y)?(b.pcdata&&b.pcdata("&"+Y,f,O,h(b,c,g,e,f)),g++):b.pcdata&&b.pcdata("&amp;",f,O,h(b,c,g,e,f));break;case "</":(m=/^([-\w:]+)[^\'\"]*/.exec(Y))?m[0].length===Y.length&&">"===c[g+1]?(g+=2,p=m[1].toLowerCase(),b.endTag&&b.endTag(p,f,O,h(b,c,g,e,f))):g=r(c,g,b,f,O,e):b.pcdata&&b.pcdata("&lt;/",f,O,h(b,c,g,e,f));break;case "<":if(m=/^([-\w:]+)\s*\/?/.exec(Y))if(m[0].length===Y.length&&">"===c[g+1]){g+=2;p=m[1].toLowerCase();b.startTag&&b.startTag(p,[],f,O,h(b,
c,g,e,f));var Ya=a.ELEMENTS[p];Ya&Bb&&(g=u(c,{name:p,next:g,eflags:Ya},b,f,O,e))}else g=q(c,g,b,f,O,e);else b.pcdata&&b.pcdata("&lt;",f,O,h(b,c,g,e,f));break;case "\x3c!--":if(!e.noMoreEndComments){for(k=g+1;k<l&&(">"!==c[k]||!/--$/.test(c[k-1]));k++);if(k<l){if(b.comment){var Za=c.slice(g,k).join("");b.comment(Za.substr(0,Za.length-2),f,O,h(b,c,k+1,e,f))}g=k+1}else e.noMoreEndComments=!0}e.noMoreEndComments&&b.pcdata&&b.pcdata("&lt;!--",f,O,h(b,c,g,e,f));break;case "<!":if(/^\w/.test(Y)){if(!e.noMoreGT){for(k=
g+1;k<l&&">"!==c[k];k++);k<l?g=k+1:e.noMoreGT=!0}e.noMoreGT&&b.pcdata&&b.pcdata("&lt;!",f,O,h(b,c,g,e,f))}else b.pcdata&&b.pcdata("&lt;!",f,O,h(b,c,g,e,f));break;case "<?":if(!e.noMoreGT){for(k=g+1;k<l&&">"!==c[k];k++);k<l?g=k+1:e.noMoreGT=!0}e.noMoreGT&&b.pcdata&&b.pcdata("&lt;?",f,O,h(b,c,g,e,f));break;case ">":b.pcdata&&b.pcdata("&gt;",f,O,h(b,c,g,e,f));break;case "":break;default:b.pcdata&&b.pcdata(n,f,O,h(b,c,g,e,f))}}b.endDoc&&b.endDoc(f)}catch(Db){if(Db!==O)throw Db;}}function n(a){var b=/(<\/|<\!--|<[!?]|[&<>])/g;
a+="";if($a)return a.split(b);for(var c=[],d=0,e;null!==(e=b.exec(a));)c.push(a.substring(d,e.index)),c.push(e[0]),d=e.index+e[0].length;c.push(a.substring(d));return c}function r(a,b,c,d,e,f){var k=C(a,b);if(!k)return a.length;c.endTag&&c.endTag(k.name,d,e,h(c,a,b,f,d));return k.next}function q(a,b,c,d,e,f){b=C(a,b);if(!b)return a.length;c.startTag&&c.startTag(b.name,b.attrs,d,e,h(c,a,b.next,f,d));return b.eflags&Bb?u(a,b,c,d,e,f):b.next}function u(b,c,d,e,f,g){var m=b.length;Ba.hasOwnProperty(c.name)||
(Ba[c.name]=new RegExp("^"+c.name+"(?:[\\s\\/]|$)","i"));for(var p=Ba[c.name],l=c.next,n=c.next+1;n<m&&("</"!==b[n-1]||!p.test(b[n]));n++);n<m&&--n;var q=b.slice(l,n).join("");if(c.eflags&a.eflags.CDATA)d.cdata&&d.cdata(q,e,f,h(d,b,n,g,e));else if(c.eflags&a.eflags.RCDATA)d.rcdata&&d.rcdata(k(q),e,f,h(d,b,n,g,e));else throw Error("bug");return n}function C(b,c){var d=/^([-\w:]+)/.exec(b[c]),e={};e.name=d[1].toLowerCase();e.eflags=a.ELEMENTS[e.name];var f=b[c].substr(d[0].length);c+=1;for(var k=b.length;c<
k&&">"!==b[c];c++)f+=b[c];if(!(k<=c)){for(var h=[];""!==f;)if(d=na.exec(f))if(d[4]&&!d[5]||d[6]&&!d[7]){for(var g=d[4]||d[6],m=!1,l=[f,b[c++]];c<k;c++){if(m){if(">"===b[c])break}else 0<=b[c].indexOf(g)&&(m=!0);l.push(b[c])}if(k<=c)break;f=l.join("")}else{var n=d[1].toLowerCase(),q=d[2]?A(d[3]):"";h.push(n,q);f=f.substr(d[0].length)}else f=f.replace(/^[\s\S][^a-z\s]*/,"");e.attrs=h;e.next=c+1;return e}}function A(a){var b=a.charCodeAt(0);if(34===b||39===b)a=a.substr(1,a.length-2);return e(d(a))}function t(b){function c(a,
b){e||b.push(a)}var d,e;return l({startDoc:function(){d=[];e=!1},startTag:function(c,k,h){if(!e&&a.ELEMENTS.hasOwnProperty(c)){var g=a.ELEMENTS[c];if(!(g&a.eflags.FOLDABLE)){var m=b(c,k);if(m){if("object"!==typeof m)throw Error("tagPolicy did not return object (old API?)");if("attribs"in m)k=m.attribs;else throw Error("tagPolicy gave no attribs");var l,n;"tagName"in m?(n=m.tagName,l=a.ELEMENTS[n]):(n=c,l=g);if(g&a.eflags.OPTIONAL_ENDTAG){var p=d[d.length-1];!p||p.orig!==c||p.rep===n&&c===n||h.push("</",
p.rep,">")}g&a.eflags.EMPTY||d.push({orig:c,rep:n});h.push("<",n);for(var q=0,r=k.length;q<r;q+=2){var u=k[q],t=k[q+1];null!==t&&void 0!==t&&h.push(" ",u,'="',f(t),'"')}h.push(">");g&a.eflags.EMPTY&&!(l&a.eflags.EMPTY)&&h.push("</",n,">")}else e=!(g&a.eflags.EMPTY)}}},endTag:function(b,c){if(e)e=!1;else if(a.ELEMENTS.hasOwnProperty(b)){var f=a.ELEMENTS[b];if(!(f&(a.eflags.EMPTY|a.eflags.FOLDABLE))){if(f&a.eflags.OPTIONAL_ENDTAG)for(f=d.length;0<=--f;){var k=d[f].orig;if(k===b)break;if(!(a.ELEMENTS[k]&
a.eflags.OPTIONAL_ENDTAG))return}else for(f=d.length;0<=--f&&d[f].orig!==b;);if(!(0>f)){for(var h=d.length;--h>f;){var g=d[h].rep;a.ELEMENTS[g]&a.eflags.OPTIONAL_ENDTAG||c.push("</",g,">")}f<d.length&&(b=d[f].rep);d.length=f;c.push("</",b,">")}}}},pcdata:c,rcdata:c,cdata:c,endDoc:function(a){for(;d.length;d.length--)a.push("</",d[d.length-1].rep,">")}})}function E(a,b,c,d,e){if(!e)return null;try{var f=xc.parse(""+a);if(f&&(!f.hasScheme()||Cb.test(f.getScheme()))){var k=e(f,b,c,d);return k?k.toString():
null}}catch(Pc){}return null}function z(a,b,c,d,e){c||a(b+" removed",{change:"removed",tagName:b});if(d!==e){var f="changed";d&&!e?f="removed":!d&&e&&(f="added");a(b+"."+c+" "+f,{change:f,tagName:b,attribName:c,oldValue:d,newValue:e})}}function I(a,b,c){var d;d=b+"::"+c;if(a.hasOwnProperty(d))return a[d];d="*::"+c;if(a.hasOwnProperty(d))return a[d]}function D(b,c){return I(a.ATTRIBS,b,c)}function K(b,c){return I(a.LOADERTYPES,b,c)}function G(b,c){return I(a.URIEFFECTS,b,c)}function L(b,c,d,e,f){for(var k=
0;k<c.length;k+=2){var h=c[k],g=c[k+1],l=g,n=null,m;if((m=b+"::"+h,a.ATTRIBS.hasOwnProperty(m))||(m="*::"+h,a.ATTRIBS.hasOwnProperty(m)))n=a.ATTRIBS[m];if(null!==n)switch(n){case a.atype.NONE:break;case a.atype.SCRIPT:g=null;f&&z(f,b,h,l,g);break;case a.atype.STYLE:if("undefined"===typeof Q){g=null;f&&z(f,b,h,l,g);break}var q=[];Q(g,{declaration:function(b,c){var e=b.toLowerCase();w(e,c,d?function(b){return E(b,a.ueffects.SAME_DOCUMENT,a.ltypes.SANDBOXED,{TYPE:"CSS",CSS_PROP:e},d)}:null);c.length&&
q.push(e+": "+c.join(" "))}});g=0<q.length?q.join(" ; "):null;f&&z(f,b,h,l,g);break;case a.atype.ID:case a.atype.IDREF:case a.atype.IDREFS:case a.atype.GLOBAL_NAME:case a.atype.LOCAL_NAME:case a.atype.CLASSES:g=e?e(g):g;f&&z(f,b,h,l,g);break;case a.atype.URI:g=E(g,G(b,h),K(b,h),{TYPE:"MARKUP",XML_ATTR:h,XML_TAG:b},d);f&&z(f,b,h,l,g);break;case a.atype.URI_FRAGMENT:g&&"#"===g.charAt(0)?(g=g.substring(1),g=e?e(g):g,null!==g&&void 0!==g&&(g="#"+g)):g=null;f&&z(f,b,h,l,g);break;default:g=null,f&&z(f,
b,h,l,g)}else g=null,f&&z(f,b,h,l,g);c[k+1]=g}return c}function J(b,c,d){return function(e,f){if(a.ELEMENTS[e]&a.eflags.UNSAFE)d&&z(d,e,void 0,void 0,void 0);else return{attribs:L(e,f,b,c,d)}}}function M(a,b){var c=[];t(b)(a,c);return c.join("")}function P(a,b,c,d){b=J(b,c,d);return M(a,b)}var Q,w,x;"undefined"!==typeof window&&(Q=window.parseCssDeclarations,w=window.sanitizeCssProperty,x=window.cssSchema);var y={lt:"<",LT:"<",gt:">",GT:">",amp:"&",AMP:"&",quot:'"',apos:"'",nbsp:"\u00a0"},ja=/^#(\d+)$/,
ka=/^#x([0-9A-Fa-f]+)$/,Ca=/^[A-Za-z][A-Za-z0-9]+$/,ga="undefined"!==typeof window&&window.document?window.document.createElement("textarea"):null,X=/\0/g,Da=/&(#[0-9]+|#[xX][0-9A-Fa-f]+|\w+);/g,la=/^(#[0-9]+|#[xX][0-9A-Fa-f]+|\w+);/,Ea=/&/g,Fa=/&([^a-z#]|#(?:[^0-9x]|x(?:[^0-9a-f]|$)|$)|$)/gi,aa=/[<]/g,ma=/>/g,Ga=/\"/g,na=/^\s*(\[[-.:\w]+\]|[-.:\w]+)(?:\s*(=)\s*((")[^"]*("|$)|(')[^']*('|$)|(?=[a-z][-\w]*\s*=)|[^"'\s]*))?/i,$a=3==="a,b".split(/(,)/).length,Bb=a.eflags.CDATA|a.eflags.RCDATA,O={},Ba=
{},Cb=/^(?:https?|geo|mailto|sms|tel)$/i,N={};N.escapeAttrib=N.escapeAttrib=f;N.makeHtmlSanitizer=N.makeHtmlSanitizer=t;N.makeSaxParser=N.makeSaxParser=l;N.makeTagPolicy=N.makeTagPolicy=J;N.normalizeRCData=N.normalizeRCData=k;N.sanitize=N.sanitize=P;N.sanitizeAttribs=N.sanitizeAttribs=L;N.sanitizeWithPolicy=N.sanitizeWithPolicy=M;N.unescapeEntities=N.unescapeEntities=e;return N})(Z);function yc(a,c,b){var d=self.location,e=S(b),e=fa(e.search);F().assert(!("__amp_source_origin"in e),"Source origin is not allowed in %s",b);var f=Oa(d),e=S(Pa(d));if("href"==c&&!R(b,"#"))return Qa(b,e);if("src"==c)return"amp-img"==a?zc(b,e,f):Qa(b,e);if("srcset"==c){var k;try{k=Xb(b)}catch(l){return F().error("sanitizer","Failed to parse srcset: ",l),b}a=k.getSources();for(c=0;c<a.length;c++)a[c].url=zc(a[c].url,e,f);return k.stringify()}return b}
function zc(a,c,b){a=S(Qa(a,c));return"data:"==a.protocol||Oa(a)||!b?a.href:za+"/i/"+("https:"==a.protocol?"s/":"")+encodeURIComponent(a.host)+a.pathname+(a.search||"")+(a.hash||"")};var Ac=/^(i?-)?amp(html)?-/,Bc=H({"AMP-CAROUSEL":["slide"],"AMP-LIST":["state"],"AMP-SELECTOR":["selected"]});
function Cc(a,c){var b=this;this.ampdoc=a;this.w=a.win;this.qa=c||a.win;this.L=[];this.ma=this.ra.bind(this);this.M=H();this.ea=T(a,"history");this.ha=[];this.Y=2E3;this.ja=T(a,"resources");this.P=H();this.wa=U(this.w,"timer");this.xa=new ec;this.F=T(this.ampdoc,"viewer");this.F.onMessageRespond("premutate",this.sa.bind(this));var d=c?jb(c.document).then(function(){return c.document.body}):a.whenBodyAvailable();this.T=this.F.whenFirstVisible().then(function(){return d}).then(function(a){return b.X(a)});
this.V=null;B().development&&(AMP.printState=this.ta.bind(this))}v=Cc.prototype;v.adoptEmbedWindow=function(a){Va(a,new Cc(this.ampdoc,a))};v.setState=function(a,c,b){var d=this;try{xa(this.P,a)}catch(e){F().error("amp-bind","Failed to merge result from AMP.setState().",e)}return c?Promise.resolve():this.V=this.T.then(function(){return Dc(d)}).then(function(a){return Ec(d,a,b)})};v.setStateWithExpression=function(a,c){var b=this;return this.V=Fc(this,a,c).then(function(a){return b.setState(a)})};
v.pushStateWithExpression=function(a,c){var b=this;return Fc(this,a,c).then(function(a){function c(){return b.setState(d)}var d=H();Object.keys(a).forEach(function(a){var c;a:{var e=b.P[a];if(void 0!==e)try{c=JSON.parse(JSON.stringify(e));break a}catch(g){ua().error("amp-bind","Failed to copy JSON ("+e+") with error: "+g)}c=null}d[a]=c});b.ea.push(c);return b.setState(a)})};
v.scanAndApply=function(a,c,b){b=void 0===b?2E3:b;var d=this,e=Gc(this,c).then(function(){return Hc(d,a)}).then(function(b){if(0<b)return Dc(d).then(function(b){return Ic(d,b,a)})});return this.wa.timeoutPromise(b,e,"Timed out waiting for amp-bind to process rendered template.")};v.X=function(a){var c=this,b=Promise.all([Jc(this),Hc(this,[a])]).then(function(){a.addEventListener("amp:dom-update",c.ma)});B().development&&(b=b.then(function(){return Dc(c).then(function(a){return c.ya(a)})}));return b};
v.numberOfBindings=function(){return this.L.reduce(function(a,c){return a+c.boundProperties.length},0)};v.Ha=function(a){this.Y=a};v.Ea=function(){return this.ea};v.sa=function(a){var c=this,b=[];return this.T.then(function(){Object.keys(a.state).forEach(function(d){c.ha.includes(d)||(delete a.state[d],b.push(d))});0<b.length&&F().warn("amp-bind","Some state keys could not be premutated because they are missing the overridable attribute: "+b.join(", "));return c.setState(a.state)})};
v.makeStateKeyOverridable=function(a){this.ha.push(a)};function Jc(a){var c=lb(a.ampdoc.getBody()),b=[];mb(c,function(a){var c=(a.getAttribute("arguments")||"").split(",").map(function(a){return a.trim()});b.push({id:a.getAttribute("id"),argumentNames:c,expressionString:a.getAttribute("expression")})});return 0==b.length?Promise.resolve(0):Kc(a,"bind.addMacros",[b]).then(function(){return b.length})}
function Hc(a,c){var b=c.map(function(b){var c=a.Y-a.numberOfBindings();return Lc(a,b,c).then(function(b){var c=b.boundElements,d=b.bindings,e=b.expressionToElements,f=b.limitExceeded;a.L=a.L.concat(c);Object.assign(a.M,e);f&&F().error("amp-bind","Maximum number of bindings reached "+("("+a.Y+"). Additional elements with ")+"bindings will be ignored.");return d})});return Promise.all(b).then(function(b){var c=Array.prototype.concat.apply([],b);return 0==c.length?c.length:Kc(a,"bind.addBindings",[c]).then(function(b){Object.keys(b).forEach(function(c){var d=
a.M[c];if(0<d.length){var e=b[c],f=F().createError('amp-bind: Expression compile error in "'+c+'". '+e.message);f.stack=e.stack;V(f,d[0])}});return c.length})})}
function Gc(a,c){B().development&&a.numberOfBindings();Pb(a.L,function(a){for(var b=0;b<c.length;b++)if(c[b].contains(a.element))return!1;return!0});B().development&&a.numberOfBindings();var b=[],d;for(d in a.M){var e=a.M[d];Pb(e,function(a){for(var b=0;b<c.length;b++)if(c[b].contains(a))return!1;return!0});0==e.length&&(b.push(d),delete a.M[d])}return 0<b.length?Kc(a,"bind.removeBindingsWithExpressionStrings",[b]):Promise.resolve()}
function Lc(a,c,b){function d(){var c=l.currentNode;if(!c)return!0;var d=c.tagName,r=Mc(a,c);f.length+r.length>b&&(r=r.slice(0,b-f.length),h=!0);0<r.length&&e.push({element:c,boundProperties:r});r.forEach(function(a){var b=a,e=b.expressionString;f.push({tagName:d,property:b.property,expressionString:e});k[e]||(k[e]=[]);k[e].push(c)});return!l.nextNode()||h}var e=[],f=[],k=H(),l=c.ownerDocument.createTreeWalker(c,NodeFilter.SHOW_ELEMENT,null,!1),h=!1;return new Promise(function(b){function c(g){var l=
!1;if(g&&!g.didTimeout)for(;1<g.timeRemaining()&&!l;)l=d();else{var n=250;for(g=0;g<n&&!l;g++)l=d()}l?b({boundElements:e,bindings:f,expressionToElements:k,limitExceeded:h}):kc(a.ampdoc,c)}kc(a.ampdoc,c)})}
function Mc(a,c){for(var b=[],d=c.attributes,e=0,f=d.length;e<f;e++){var k;a:{var l=a,h=d[e];k=c;var g=k.tagName,n=h.name;if(2<n.length&&"["===n[0]&&"]"===n[n.length-1]){n=n.substr(1,n.length-2);if(l.xa.canBind(g,n)){k={property:n,expressionString:h.value};break a}l=F().createError("amp-bind: Binding to ["+n+"] on <"+g+"> is not allowed.");V(l,k)}k=null}k&&b.push(k)}return b}
function Fc(a,c,b){return a.T.then(function(){Object.assign(b,a.P);return Kc(a,"bind.evaluateExpression",[c,b])}).then(function(a){var b=a.result;if(a=a.error)throw b=F().createError("amp-bind: Expression eval failed with error: "+a.message),b.stack=a.stack,V(b),b;return b})}
function Dc(a){var c=Kc(a,"bind.evaluateBindings",[a.P]);return c.then(function(b){var c=b.results,e=b.errors;Object.keys(e).forEach(function(b){var c=a.M[b];if(0<c.length){var d=e[b];b=F().createError('amp-bind: Expression evaluation error in "'+b+'". '+d.message);b.stack=d.stack;V(b,c[0])}});return c})}
v.ya=function(a){this.L.forEach(function(c){var b=c.element;c.boundProperties.forEach(function(c){var d=a[c.expressionString];if(void 0!==d){var f=c.property;c=c.expressionString;var k=b.tagName,l=Bc[k];if(!l||!l.includes(f)){switch(f){case "text":l=b.textContent;d=String(d);l=l.trim()===d.trim();break;case "class":for(var l=[],h=0;h<b.classList.length;h++){var g=b.classList[h];Ac.test(g)||l.push(g)}h=[];Array.isArray(d)?h=d:"string"===typeof d?(g=d.trim(),0<g.length&&(h=g.split(" "))):(g=F().createError('amp-bind: "'+
d+'" is not a valid result for [class].'),V(g,b));a:if(g=h,l.length!==g.length)l=!1;else{for(var h=(Array.isArray(l)?l:oa(l)).sort(),g=(Array.isArray(g)?g:oa(g)).sort(),n=0;n<l.length;n++)if(h[n]!==g[n]){l=!1;break a}l=!0}break;default:l=b.getAttribute(f),l=!0===d?""===l:!1===d?null===l:l===d}l||F().warn("amp-bind","Default value for <"+k+" ["+f+']="'+c+'"> '+("does not match first result ("+d+"). We recommend ")+"writing expressions with matching default values, but this can be safely ignored if intentional.")}}})})};
function Nc(a,c){var b=[];a.forEach(function(a){var d=a.previousResult,f=c[a.expressionString];void 0===f||Sa(f,d,3)||(a.previousResult=f,b.push({boundProperty:a,newValue:f}))});return b}function Ec(a,c,b){var d=a.L.map(function(d){return b&&"AMP-STATE"==d.element.tagName?Promise.resolve():Oc(a,c,d)});return Promise.all(d)}function Ic(a,c,b){var d=[];a.L.forEach(function(e){b.forEach(function(b){b.contains(e.element)&&d.push(Oc(a,c,e))})});return Promise.all(d)}
function Oc(a,c,b){var d=b.element,e=Nc(b.boundProperties,c);return 0===e.length?Promise.resolve():a.ja.mutateElement(d,function(){var b={},c,l;e.forEach(function(a){var e=a,f=e.boundProperty,e=e.newValue,g;a:{var h=f.property;switch(h){case "text":d.textContent=String(e);"TEXTAREA"==d.tagName&&(d.value=String(e));break;case "class":g=[];for(h=0;h<d.classList.length;h++){var k=d.classList[h];Ac.test(k)&&g.push(k)}Array.isArray(e)||"string"===typeof e?d.setAttribute("class",g.concat(e).join(" ")):
null===e?d.setAttribute("class",g.join(" ")):(g=F().createError('amp-bind: "'+e+'" is not a valid result for [class].'),V(g,d));break;default:var k="INPUT"==d.tagName&&h in d,A=d.getAttribute(h),t=!1;if("boolean"===typeof e)k&&d[h]!==e&&(d[h]=e,t=!0),e&&""!==A?(d.setAttribute(h,""),t=!0):e||null===A||(d.removeAttribute(h),t=!0);else if(e!==A){try{var E=String(e),z=d.tagName.toLowerCase(),I=h.toLowerCase();g="src"==I||"href"==I||"srcset"==I?yc(z,I,E):E}catch(K){E=F().createError('amp-bind: "'+e+'" is not a '+
("valid result for ["+h+"]"),K),V(E,d)}void 0!==g&&(d.setAttribute(h,g),k&&(d[h]=g),t=!0)}if(t){g={name:h,value:e};break a}}g=null}var D=g;D&&(b[D.name]=D.value,f=f.property,"width"==f?c="number"===typeof e&&isFinite(e)?Number(e):c:"height"==f&&(l="number"===typeof e&&isFinite(e)?Number(e):l))});void 0===c&&void 0===l||a.ja.changeSize(d,l,c);if("function"===typeof d.mutatedAttributesCallback)try{d.mutatedAttributesCallback(b)}catch(g){var h=F().createError("amp-bind: Applying expression "+("results ("+
JSON.stringify(b)+") failed with error"),g);V(h,d)}})}v.ra=function(a){var c=this,b=a.target;(a=b.parentNode)&&"AMP-LIST"==a.tagName?ua().info("amp-bind","Skipping DOM_UPDATE rescan of:",b):Gc(this,[b]).then(function(){return Hc(c,[b])}).then(function(){})};function Kc(a,c,b){var d=a.w;a=a.qa;if(d.Worker){var e;e=Wa(d);Xa(e,e,"amp-worker",vc);d=U(d,"amp-worker");c=wc(d,c,b||[],a)}else c=Promise.reject("Worker not supported in window.");return c}
v.ta=function(){var a=[],c=JSON.stringify(this.P,function(b,c){if(pa(c)){if(a.includes(c))return"[Circular]";a.push(c)}return c});F().info("amp-bind",c)};v.Fa=function(){return this.T};v.Ia=function(){return this.V};(function(a){a.registerServiceForDoc("bind",Cc);a.registerElement("amp-state",Sb);a.registerElement("amp-bind-macro",Qb)})(self.AMP);
})});
//# sourceMappingURL=amp-bind-0.1.js.map

